### ISSUE TITLE
Notification after push

### ISSUE THREAD

**Issue by flinux** [arleyandrada/PushClient#1]
Hi,
i can't understand how it works.
I bought the plugin and after installed I successfully receive the push message from google, but no notification appears.

I read this in the app.js documentation:

// Notification properties:
// "alert" (String) to text message - or "text" to Android
// "sound" (String) to sound file to play - "default" to Android default sound
// "badge" (Int) to badge count indicator
// "content-available" (Int) to iOS background notification
// -->> Requires set remote-notification UIBackgroundModes in tiapp.xml
// "notificationId" (Int) to Android notification identification
// "title" (String) to override Android notification title - default app name
// "ticker" (String) to override Android ticker message - default alert message
// "vibrate" (Boolean) to use default Android device vibration
// "lights" (Boolean) to use default Android device lights
// "smallIcon" (String) set small icon to Android notification from assets
// "largeIcon" (String) set large icon to Android notification from local file or url
// "category" (String) to iOS 8 interactive notification
// "ledARGB" (Color) to change default Android device light color
// "ledOnMS" (Int) to change default Android device light blink on time
// "ledOffMS" (Int) to change default Android device light blink off time

But where i have to set this variables ?
Can you provide a full example with notifications ?

Thank you,
Francesco.

**Comment by arleyandrada** [comment]
Hi Francesco,

The "notification properties" are the "JSON payload properties" sent from your push notification provider.

Sample:

```
{
"alert" : "Hello world!",
"content_available" : 1,
"badge" : 10,
"largeIcon" : "http://rocketdock.com/images/screenshots/supermario.png",
"vibrate" : true,
"my-custom-property" : "my custom data"
}
```

Try it.
Please let me know if it works for you.

Regards,

Arley

**Comment by flinux** [comment]
Thank you, it works!
But if I launch your module from a service (with BOOT_RECEIVER) and the application is closed, I can see the notification and when I click it the service launch the application and no callbacks are called.
I think that your module doesn't set the intent passed to the application activity with the push data.

Please let me know.

Regards,
Francesco.

**Comment by arleyandrada** [comment]
You don't need to wake the app with BOOT_RECEIVER to allow it to receive notification when it is closed.

My module request the required permissions, register and implements the GCM receivers.

When you click on the notification, it fires an Intent to a custom activity handled by my module... and after that, my module fires the MODE_CLICK through the EVENT_CALLBACK event.

You will not receive the callback event if the "addEventListerner" and "registerPush" methods (from my module) is not fired when the app starts.

Maybe you can share your project with me, or a minimal version of it.
