### ISSUE TITLE
Custom icon with Android 5.0+ doesnt seem to work

### ISSUE THREAD

**Issue by rollsroyc3** [arleyandrada/PushClient#101]
For Android 5.0+ we must use a transparent background with white icon. I have created these icons and placed them in drawables. Also updated the push payload to use the icon name with file extension but I still get the generic icon. Can you confirm if this is a bug with pushclient?

**Comment by rollsroyc3** [comment]
Here is a post on Appcelerator QA with more detail, thanks!

https://community.appcelerator.com/topic/3684/android-5-0-notification-icons-are-gray-circle-with-white-icon-drawables-w-custom-icon-not-working

**Comment by arleyandrada** [comment]
Take a look at this closed issue:
https://github.com/arleyandrada/PushClient/issues/52
