### ISSUE TITLE
Android 6.0 Icon not showing up

### ISSUE THREAD

**Issue by abdielou** [arleyandrada/PushClient#102]
I've looked at issue #52 and it works perfectly with any device that has Android 5 or less, but I have a device with Android 6 and it is not showing the icon. It does shows the `largeIcon` but not the `smallIcon`.

**Comment by abdielou** [comment]
I think it has something to do with Android version 21+. I've seen people having issues with their icons but only because their icons are white. That's not my case. Anyways, I set my `targetSdkVersion=20` and  that fixed the issue with Android 6.0. I can live with that for the mean time but it is not desirable.

**Comment by bombh** [comment]
Hello.
I run into the same issue. The problem is that targetSdkVersion 20 does not seem compatible with Titanium 4,1,0 GA. Any other suggestion ?
Thank you

**Comment by arleyandrada** [comment]
I'm sorry for the late reply. I've been missing in recent months because of health problems and unable to work on my projects. I am currently checking and solving all pending issues. Please check back me if I can help in something else. Thank you!

**Comment by arleyandrada** [comment]
Hi Abdiel,

I sent a email to you containing a new version of PushClient module.
Please, check if your issues was resolved.

Regards,

Arley

**Comment by arleyandrada** [comment]
Hi bombh,

I was unable to identify your email and also your PushClient license, only by your github username, to be able to send a new version of PushClient module to you.

I released a new version of my module, but the Appcelerator Marketplace is very lazy.

Regards,

Arley

**Comment by bombh** [comment]
Hi Arley

thank you for your email.

"I was unable to identify your email and also your PushClient license, only by your github username, to be able to send a new version of PushClient module to you."

here is the receipt from Appcelerator
Do you need any other information ?

Thank you
Fabrice Roelens

---

De : Open Mobile Marketplace [noreply@appcelerator.com]
Envoyé : lundi 21 septembre 2015 20:34
À : Fabrice Roelens
Objet : Your receipt for PushClient on Appcelerator

Hello Fabrice Roelens,

You successfully purchased PushClient! You can start using PushClient
from your Appcelerator MyProducts page:
https://marketplace.appcelerator.com/myproducts

If your order today was for a free trial, the length of your trial
is shown below, and your first invoice will be due at the end of
this trial period.

Order Details
Product name: PushClient
Product edition: One Time Edition
Free trial: None
Billing period: One Time

You can manage your purchase and add users to PushClient right from the
Account section on Appcelerator by visiting:
https://marketplace.appcelerator.com/account/apps/

To learn how to incorproate your new module into Titanium, click the link below:
http://wiki.appcelerator.org/display/tis/Using+Titanium+Modules

If you have any questions please email us at marketplace-support@appcelerator.com.

Code Strong,

The Appcelerator Team

**Comment by danny005** [comment]
Is this fixed in Version 1.11 available on the Appcelerator Marketplace?

**Comment by arleyandrada** [comment]
I hope so. I was unable to test in a real Android 6.0 device.

**Comment by danny005** [comment]
Ok, thanks. Just want to know if the current version on the Marketplace is the latest one that you have submitted.

So I guess you have tested it on the standard Android Emulator with Google API Level 23? Did you manage to test it on Genymotion and Android 6.0 with Gogole APIs?

**Comment by arleyandrada** [comment]
Yes, the latest version (1.11) is available from Appcelerator Marketplace.

With Genymotion was possible to emulate the Android 6.0 preview devices, but with GApps for Android 5.1.

**Comment by danny005** [comment]
Sorry if this goes offtopic: on Genymotion you can flash the Android 6.0 preview device (e.g. Nexus 5) with GApps for Android 5.1. (gapps-L-4-21-15.zip or gapps-lp-20150314.zip) ? Didn't know that. Will try too.

**Comment by arleyandrada** [comment]
:-) Yes.
Best reference: https://gist.github.com/wbroek/9321145
Use: gapps-L-4-21-15.zip

**Comment by spinn** [comment]
Has anybody been able to get this working on 6.0+? I've been trying but whatever I do I always get a white square icon, even though the icon I'm using is on transparent background. I'm also using the latest Titanium SDK (5.1.2GA) so I can't set targetSdkVersion to 20.

**Comment by abdielou** [comment]
@arleyandrada just to confirm that I am now able to get the appropriate icon shown with Android 6. Issue #52 was of great help regarding file location. The other issue I was having was related to the image I was using. My image did not have a transparent background and thus a white square was showing. Once I fixed my images the correct logo was shown.

@spinn take a look at #25 as your problem might be the icon location. I put mines at "<project_root>/platform/android/res/drawable-*/push_icon.png"

A third issue I was having was not setting the correct meta data on the manifest. You must add 

```
<meta-data android:name="com.parse.push.notification_icon" android:resource="@drawable/push_icon"/>
```

to your Android manifest (inside tiapp.xml). Checkout this post from Parse.com https://parse.com/tutorials/android-push-notifications

Finally here's an example Parse.com Push JSON payload:

```
{
    "alert": "Your Message Here",
    "smallIcon": "push_icon",
    "largeIcon": "https://example.com/myLargeIcon.png"
}
```

**Comment by Rajveer123** [comment]
Hello @arleyandrada ,
I am using your latest 1.21 module in my Titanium Application and my requirement is to implement rich media to Push Notification using onesignal i.e
Small / Large Icons
Background Image
Action Buttons etc 

So does it possible to implement last two things using your module as i have already done with first thing using your module.

If yes then which property name I have to use can you please suggest me for background Image and Action buttons.

Looking forward to your valuable feedback.
Thanks in Advance
