### ISSUE TITLE
Sound file needs extension on iOS but not on Android

### ISSUE THREAD

**Issue by abdielou** [arleyandrada/PushClient#103]
I just noticed that I need to specify the extension (`"sound": "mySound.wav"`) to make it work on iOS but on Android I cannot specify the extension (`"sound": "mySound"`).

That being the case, there's no way to send homogeneous Push messages across platforms. Is there a way to fix this other than sending 2 pushes, one for each platform?

**Comment by arleyandrada** [comment]
Great idea! I will release it in next version.

I'm sorry for the late reply. I've been missing in recent months because of health problems and unable to work on my projects. I am currently checking and solving all pending issues. Please check back me if I can help in something else. Thank you!

**Comment by abdielou** [comment]
Great thanks for adding this.
And good to have you back.

**Comment by arleyandrada** [comment]
Hi Abdiel,

I sent a email to you containing a new version of PushClient module.
Please, check if your issues was resolved.

Regards,

Arley
