### ISSUE TITLE
Android custom icons for 5.0+

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#108]
For lollipop you custom push notifications you must use white transparent icons, I believe I have done everything needed for this to work but I still get a generic gray circle with white square for my icon. Can you please confirm if this is an issue with your module? I have already bought this product twice and plan to buy it again but need this fixed first, thanks! I thought it might be a Titanium issue at first but now Im not so sure: https://community.appcelerator.com/topic/3684/android-5-0-notification-icons-are-gray-circle-with-white-icon-drawables-w-custom-icon-not-working

asked by Andrew Royce on 07/12/2015

**Comment by arleyandrada** [comment]
Take a look at this closed issue:
#52
