### ISSUE TITLE
Notification doesnt get displayed in notification tray

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#11]
Hello,

Here is my source code, [PRIVATE]
I am using https://github.com/benbahrenburg/LocalNotify for notification. 

Please help us in solving the issue. 

Thanks,

**Comment by arleyandrada** [comment]
Hi,

What is the problem with this source code?
Which issue are you talking about?

There is some problem related with my PushClient module?

Regards,

Arley

**Comment by somefakeuser** [comment]
I'm not getting the notification when  the app is not open.

Also guide me how to get the notification message on click work.

Thanks,

**Comment by arleyandrada** [comment]
What is the push notification server / service are you using?
What is the message you are sending to the device?

Are you running your app on iOS or Android?
What is the Titanium SDK version you are using in your app?

Are you correctly receiving the push notification when in foreground?

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

Comments inline.

What is the push notification server / service are you using?
// We are using APN default notification on our own server, we are not using any third party services like Amazon.

What is the message you are sending to the device?
//Text Message only considering payload guidelines of APN. 

Are you running your app on iOS or Android?
// iOS

What is the Titanium SDK version you are using in your app?
// 3.2.3.GA

Are you correctly receiving the push notification when in foreground?
// Yes we are receiving push notification when its in foreground, but it doesn’t prompt or alerts with sound when notification arrives.

**Comment by arleyandrada** [comment]
When in foreground, is a default behavior in iOS (is not an choice from my module), not show any notification alert or sound in your device; However you can register and show a "local notification" or play any sound.

When in background, is a default behavior in iOS, show the message in notification center with the text and sound defined in your sent message from apn, regardless of the module or your app source code.

If you are not viewing any message in notification center, may you can check:
- The message sent from your own push server must have an required "alert" attribute to define the text message and an optional "sound" attribute to define the sound to play; Something like:

```
{
alert : "Hello world!",
sound : "bingbong.aiff"
}
```
- When you have installed the app in your device was asked to the user an permission to receive remote push notifications; If it was denied, you can change or check this at iOS settings app or just remove and reinstall your app.

Please let me know if it works to you.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hello Arley,

I did the alert of entire "alert('Callback in Foreground:\n\n' + JSON.stringify(event));" 

I have attached the screenshot of payload from server. 

Please let us know if we need to change anything from server side payload.

Thanks,

![img_1316](https://cloud.githubusercontent.com/assets/12264970/7486907/c8e8b59a-f383-11e4-94dd-898c681dddf4.jpg)

**Comment by arleyandrada** [comment]
Hi,

Great idea to share the screenshot with entire received payload!

You really need to add the "alert" and (optional) the "sound" info within the payload sent from your server.

Sorry by my poor english.

Check the attached images.

![2014-08-08 16 14 09](https://cloud.githubusercontent.com/assets/1809866/7486927/0a68ada4-f384-11e4-9c65-1f2e10656c04.png)
![2014-08-08 16 15 31](https://cloud.githubusercontent.com/assets/1809866/7486933/1122535c-f384-11e4-813b-27ae0dbf39bd.png)
![2014-08-08 16 15 47](https://cloud.githubusercontent.com/assets/1809866/7486935/16b21154-f384-11e4-82bd-5bd28d5e02d6.png)

**Comment by somefakeuser** [comment]
Hello,

Thanks for sharing the screenshots.

Can you share the app side source code which you have used generate these screenshots?

Thanks,

**Comment by somefakeuser** [comment]
Sure!

It is an sample project with my PushClient module connected to Parse.com service.

[PushClient on GitHub](https://github.com/arleyandrada/PushClient)

**Comment by arleyandrada** [comment]
Sure!

It is an sample project with my PushClient module connected to Parse.com service.

[PushClient on GitHub](https://github.com/arleyandrada/PushClient)

**Comment by somefakeuser** [comment]
Hello,

Thanks for the source code.

Will test and get back to you if there is any issues.

Thanks,

**Comment by somefakeuser** [comment]
Hi Arley,

We tried the code you shared, it worked well but still we are facing following issues.
1. When app is in background, alert you have put for the notification doesn’t work. We are trying to save that data in local cache, which we are not able to achieve. 
2. When i click on notification, i am not able to perform the actions based on data receive through notification. 

Please help me with this issues.

**Comment by arleyandrada** [comment]
Hi,

Have you make a test with the provided sample project?
Work fine with my sample project or are you facing the same problem?

Where in your source code did you put the call to "registerPush" method?

It's an yet "undocumented" requirement from PushClient module is to instantiate it, attach events and call "registerPush" method within "app.js" (non-alloy), "alloy.js" (alloy) or "index.js" (main controller) to able it to deal with the app initialization. Don't write code to avoid "duplicated" call to "registerPush" method.
