### ISSUE TITLE
The 'br.com.arlsoft.pushclient' module is not supported by Titanium SDK 5.1.1.GA

### ISSUE THREAD

**Issue by donCarlosOne** [arleyandrada/PushClient#110]
I'm seeing this message in my module properties when doing a new build (but it doesn't seem to complain when building), but I'm having problems with the module on devices with Android 4.4.2 when built with 5.1.1.GA (Andorid 5.1 works fine).

**Comment by donCarlosOne** [comment]
On a side note, can you give me a build that selectively compiles google-play-services-base.jar and google-play-services-gcm.jar, instead of google-play-services.jar.  This is creating a conflict with ti.admob, which now uses the selective compile.  The only way I can get push messaging to work is by disabling and building without ti.admob, since it is using the selective compile and no longer references google-play-services.jar.  When building with both, the dexer complains that a number of admob classes are already installed (because they exist in google-play-services.jar, which is loaded by pushclient).  Maybe you've done this already.  The latest version of pushclient that I have is 1.10 - and I don't seem to be able to download any verison at all now via Appcelerator Marketplace, even though it shows as a purchased module in my account (charles@harleybass.com).

**Comment by arleyandrada** [comment]
Yes, exactly! I'm working in a new release with this and others issues and new features. Thanks!

**Comment by nothingatalldotnet** [comment]
Any idea when the next update will be out? If there is a conflict with ti.admob then it's not something I can use. Cheers!

**Comment by arleyandrada** [comment]
Wait for the new version that will be released this weekend. Thanks!

**Comment by arleyandrada** [comment]
Hi domCarlosOne,
Hi nothingatalldotnet,

I was unable to identify your email and also your PushClient license, only by your github username, to be able to send a new version of PushClient module to you.

I released a new version of my module, but the Appcelerator Marketplace is very lazy.

Regards,

Arley

**Comment by donCarlosOne** [comment]
Hi Arley

I’m registered on Appcelerator Marketplace as charles@harleybass.com

**Comment by arleyandrada** [comment]
Hi Charles,

I sent a email to you containing a new version of PushClient module.
Please, check if your issues was resolved.

Regards,

Arley

**Comment by donCarlosOne** [comment]
Thanks Arly.  I got the email.  I’ll try an integration with it later today and will confirm if it’s working.
