### ISSUE TITLE
Compatibility with analytics.google

### ISSUE THREAD

**Issue by vasilestefirta** [arleyandrada/PushClient#113]
Hello, 
My project uses both PushClient and analytics.google module (https://github.com/Sitata/titanium-google-analytics). When I try to run the app I get the following error (it disappears after I remove the ti.map module):

[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/LifecycleDelegate;
[ERROR] :   at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :   at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :   at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] :   at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] :   at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR] :   at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] :   at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :   at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :   at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :   at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR] :   at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR] :   at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR] :   at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  1 error; aborting
2016-01-11T22:57:08.834Z | TRACE  | titanium exited with exit code 1
2016-01-11T22:57:08.835Z | ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/vasilestefirta/.appcelerator/install/5.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:92:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
2016-01-11T22:57:08.836Z | TRACE  | Sending exit signal to titanium process:  38227

Could you please give me a solution for this?

P.S. I know you have previously released a fix for the ti.map compatibility issue, so hopefully you'll be able to provide a solution for the current issue as well :)

Titanium SDK: 5.1.1
Genymotion Emulator (with Google Play Services installed): Android 5.1.0 - API 22

Thanks!

**Comment by arleyandrada** [comment]
It is required to change the titanium-google-analytics module and update its google play services version.

Again I am without my macbook right now, but next week I can try to generate a fork of this module and help you with the Google Play Services update.

**Comment by vasilestefirta** [comment]
Just a quick reminder :) Will you be able to help with the Google Play Services issue this week?
Thanks!

**Comment by arleyandrada** [comment]
Try to use the "Titanium Google Analytics" module from my forked repository
https://github.com/arleyandrada/titanium-google-analytics
