### ISSUE TITLE
couldn't find module: br.com.arlsoft.pushclient for architecture: x86_64

### ISSUE THREAD

**Issue by Garridovic** [arleyandrada/PushClient#114]
Hello Arley,

Let me first of all for their good work with the PushClient module for Appcelerator. 

I have tested it in a Iphone 4s and it worked like a charm but in iphone 5s the module throws the 64 bit problem exception : Script Error Couldn't find module: br.com.arlsoft.pushclient for architecture: x86_64. I have seen the same issue in github, https://github.com/arleyandrada/PushClient/issues/109 , but you didn't provide and an answer so I guess that I need to contact you with the Appcelerator Marketplace receipt info. My name in Appcelerator is ILIBERI Adai and the email is estadisticasweb@iliberi.com. I attach simulator screenshot with error although I know that Iphone simulator does not provide push feature. 

— EMAIL DATA — 

Hello ILIBERI Adai,

You successfully purchased PushClient! You can start using PushClient
from your Appcelerator MyProducts page:
https://marketplace.appcelerator.com/myproducts

If your order today was for a free trial, the length of your trial
is shown below, and your first invoice will be due at the end of
this trial period.

Order Details
Product name: PushClient
Product edition: One Time Edition
Free trial: None
Billing period: One Time

You can manage your purchase and add users to PushClient right from the
Account section on Appcelerator by visiting:
https://marketplace.appcelerator.com/account/apps/

To learn how to incorproate your new module into Titanium, click the link below:
http://wiki.appcelerator.org/display/tis/Using+Titanium+Modules

If you have any questions please email us at marketplace-support@appcelerator.com.

Code Strong,

The Appcelerator Team

— — 

Greetings,
Garridovic

![captura de pantalla 2016-01-14 a las 16 33 27](https://cloud.githubusercontent.com/assets/8438211/12347844/2a78d9f6-bb62-11e5-8872-0ab9b3c754b2.png)

**Comment by arleyandrada** [comment]
Yes, there is a real problem!!
Please, try to work with previous version until I can fix it (sent to you by email).
Sorry by the inconvenience.

**Comment by arleyandrada** [comment]
Hi,

I could not find any problem with my module related to 64 bit compatibility.
It was correctly build and published with x86_64 symbols.

Check by yourself:

http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Module_64-bit_Support

cd /PATH/TO/MODULE/
xcrun lipo -info build/lib.br.com.arlsoft.pushclient.a

"Architectures in the flat file: libbr.com.arlsoft.pushclient.a are: armv7 i386 x86_64 arm64"

Are you using the Liveview feature?
There is a bug in Liveview and is unable to run iOS apps with my module.
Disable the Titanium Liveview and try again.

Regards,

Arley
