### ISSUE TITLE
Android 6.0 smallIcon shows as white square

### ISSUE THREAD

**Issue by spinn** [arleyandrada/PushClient#116]
This seems to be the same issue as #102 which doesn't seem to be fixed yet, largeIcon appears as expected, but no matter what I do, smallIcon always appears as a white square.

**Comment by arleyandrada** [comment]
Hi Spinn,

Please, share with me the image used as smallicon and try to use the "mario.png" image from my sample project (https://github.com/arleyandrada/PushClient/blob/master/platform/android/res/drawable/mario.png).

Did you put the png image in the "platform/android/res/drawable" project path?

Regards,

Arley

**Comment by arleyandrada** [comment]
Large icon from URL and small icon with default app icon:

```
{
"alert" : "Hello world!",
"largeIcon" : "http://rocketdock.com/images/screenshots/supermario.png"
}
```

Large icon from assets folder ("/app/assets/android" for alloy or "/Resources/android" for classic):

```
{
"alert" : "Hello world!",
"largeIcon" : "mario.png"
}
```

Custom small icon from resources (required do put png image in "/platform/android/res/drawable"):

```
{
"alert" : "Hello world!",
"smallIcon" : "mario"
}
```

Combined small icon and large icon:

```
{
"alert" : "Hello world!",
"smallIcon" : "mario",
"largeIcon" : "http://rocketdock.com/images/screenshots/supermario.png"
}
```

**Comment by spinn** [comment]
Oops, my bad, sorry, I didn't put the image in res/drawable, I mistakenly put it in resources/android.

**Comment by Rajveer123** [comment]
@arleyandrada ,

Can i set Background large Image and Action buttons using PushClient
 module.
