### ISSUE TITLE
New android specific error

### ISSUE THREAD

**Issue by Narsliss** [arleyandrada/PushClient#117]
I am getting the following error when I send a push notification to an andorid device. And it crashes the app.

[ERROR] :  AndroidRuntime: FATAL EXCEPTION: main
[ERROR] :  AndroidRuntime: Process: com.myapp.myapp, PID: 3994
[ERROR] :  AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package com.myapp.myapp: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.myapp.myapp user=UserHandle{0} id=43 tag=null score=0 key=0|com.myapp.myapp|43|null|10336: Notification(pri=0 contentView=com.myapp.myapp/0x1090078 vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 vis=PRIVATE))
[ERROR] :  AndroidRuntime:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)

Any help would be appreciated.

**Comment by arleyandrada** [comment]
Hi Narsliss,

There is nothing in this error log that suggests an error within my PushClient module.

Please, provide more info about your project... sample source code... full console log... another modules used in your project...

Regards,

Arley

**Comment by Narsliss** [comment]
Hi Arley,
This was actually resolved by rebooting my device.  Apparently something got corrupted in the notification system and a reboot cleared the error out.

Thanks for the time
