### ISSUE TITLE
unregisterPush

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#12]
The module seems to work great, the only thing I can’t figure out is how to tell if the unregisterPush() method is successful or not.

**Comment by arleyandrada** [comment]
Hi,

With iOS I could not figure out how to check if unregisterPush method was successfull.
To keep a common behavior, with Android I decided to not fire a successfull unregister calback too.

Please let me know if this behavior is a real problem to your app.

Regards,

Arley Maria
