### ISSUE TITLE
Not receiving notification when application not running in background (some phones)

### ISSUE THREAD

**Issue by sulthankareem** [arleyandrada/PushClient#120]
Hi sir,
 I have used your module. I feels some problem with this module. The application didn't deliver notification when application is not running in background, but no problem with some phones. My phone didnt receive notification, while application is not running in background. Working fine when application running in background

My Phone model: xiaomi redmi 2

**Comment by arleyandrada** [comment]
Hi,

Let's check somethings:

By default, the push notification is not shown in the notification tray when your app is in foreground. To iOS is a required behavior, to Android is a mimic from my module. But to Android, when receiving the push notification, you can call the showLocalNotification method and force to show a local notification in your notification tray.

`PushClient.showLocalNotification(event.data);`

When your app is in background, but is running / active, the notification is shown in notification tray without problems and your app continues to receive the callback.

When your app is not running, the notification is shown in notification tray without problems, but your app does not receive the callback until the user clicks on the received notification. But to iOS, if your push notification payload uses the "background notification feature" your app continues to receive the callback... and it is not possible to mimic this feature to Android.

When your app was killed by the user... different from not running or background... the iOS blocks all the push notifications messages, until the phone or the app is restarted. There is no problem like that with Android, that continues to work like "not running" described above.

Please, check the following related closed issues:

https://github.com/arleyandrada/PushClient/issues/111
https://github.com/arleyandrada/PushClient/issues/87
https://github.com/arleyandrada/PushClient/issues/1
https://github.com/arleyandrada/PushClient/issues/11

Regards,

Arley

**Comment by arleyandrada** [comment]
By the way... all described restrictions are required behaviors from iOS or Android or restriction imposed by the Titanium platform.

**Comment by sulthankareem** [comment]
I am discussing Android only. I already mentioned the mobile model, where I check the notification.Did your module have any problem like this? or is this the problem of my mobile model?

**Comment by arleyandrada** [comment]
So far, I don't know any problems with push notifications related to the device model.

Please, check and share with me the full log when your xiaomi device receives the push notification in foreground... and after receiving successful in background.

**Comment by arleyandrada** [comment]
Googling I found a "problem" with xiaomi devices when receiving push notifications in background, but OK to foreground.

> Why can’t I receive push notification when I quit the Line app or WhatsApp?
> A: Normally, push notification is available only when the chatting apps are in use or running in the backend. If you sign out of the apps or clear the RAM of these apps, it will result in the unavailability of push notification.
> If you want to receive push notification, please lock these chatting apps when they clear up, and enable the app auto-start option.
> Go to "Security" >> "Permission" >> "Auto-start Management" >> add auto-start apps
> To enable push notification in the status bar, go to "Settings" >> "Notifications" >> "Manage Notifications" >> Open WhatsApp >> "Show in Status Bar" (switch on)
> Long-tap the Menu key to enter the recent apps backend. Drag down the app icon to lock it, so it will not be cleared in the following clear-up operation.

**Comment by arleyandrada** [comment]
Xiaomi for security purposes disables the Notification for each Application. Follow these steps to receive messages in background once they quit the app using cleaner.
- Enable Autostart
- Enable Floating and Lock Screen Notification

**Enable AutoStart**
- Open Security App.
- Got to Permissions, then Click on Auto Start Management.
- Add/Enable auto start apps (e.g. Whatsapp).

**Enable Floating and Lock Screen Notification**
- Open Settings App.
- Click on Notifications, then click on Manage Notifications.
- Tap on the App which you are looking for (e.g. WhatsApp).
- Enable Show in notification shade / Show on lockscreen and in drop down option.

For Reference check this out : http://support.hike.in/entries/55998480-I-m-not-getting-notification-on-my-Xiaomi-Phone-For-MIUI-6-
