### ISSUE TITLE
Issues when Titanium sdk updated

### ISSUE THREAD

**Issue by visihinpv** [arleyandrada/PushClient#125]
Hi,
I have incurred an issue when i update my android sdk to 5.1.1 GA. The problem is when i invoke the pushSubscribe() function got an error like "Failed resolution of: Lcom/google/android/gms/gcm/GoogleCloudMessaging;". Please help me to solve this issue. I need urgent reply for this question. Please help me fast.
  Prior to my sdk update it works without  any issue. I have the latest pushClient version.

**Comment by visihinpv** [comment]
Screen shot of the console is given below
![screen shot 2016-04-27 at 10 51 27 am](https://cloud.githubusercontent.com/assets/18673755/14842584/2d4ab8ac-0c66-11e6-8055-c50a7869adf3.png)

**Comment by arleyandrada** [comment]
Check the Push Client version 1.13 (latest version) released in next days.
