### ISSUE TITLE
onesignal push android vibrate question

### ISSUE THREAD

**Issue by kimjw0820** [arleyandrada/PushClient#129]
Hello!

i have a question..
i use onesignal push service
but onesignal do not have a REST API option per notification to set vibration for android
supported option to client side with our https://documentation.onesignal.com/docs/android-notification-customizations#background-data-and-notification-overriding

How can I solve using pushclient?

Thank you!

**Comment by kimjw0820** [comment]
i solved.
field option 'android_sound' => 'default'

i'm sorry ^^ Thank you

**Comment by aniruddhasm** [comment]
@kimjw0820  Were exactly you wrote this line ?

**Comment by arleyandrada** [comment]
Hi @aniruddhasm, the "sound" (not "android_sound") is a JSON payload attribute which you send from your app backoffice or straight from your push notification provider.

You can set it with "default", to use the Android default sound to received notification, or use a custom audio file.

Put your custom audio file (wav or mp3) within the raw resource folder:

```
/platform/android/res/raw/youraudiofile.wav
```

Send a JSON payload data like below:

```
{
"alert" : "Custom sound",
"sound" : "youraudiofile"
}
```

or

```
{
"alert" : "Custom sound",
"sound" : "default"
}
```
