### ISSUE TITLE
Parse.com = Recebimento do push

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#13]
Tudo bem Arley,

Obrigado pelo email e pelo módulo. 
O seu módulo esta funcionando muito bem, mas estou precisando de uma ajuda sua.
Você colocou um exemplo do Parse no seu código e eu o estou usando para desenvolver o meu app.
Eu mando as informações para o Parse com o channel, deviceId e tudo mais e funciona perfeitamente, e o channel até aparece na dashboard de push do Parse. Eu escolho o meu channel de teste e envio push mas ele não chega.
Tudo funciona certinho menos o recebimento do push.

Você saberia me dizer que problema poderia ser isso?
Sei que o exemplo do parse não faz parte do módulo e você o colocou lá somente para nos ajudar, mas eu estou quebrando a cabeça com isso aqui e não consigo entender o porque. 

Muito obrigado.
Att,

**Comment by arleyandrada** [comment]
Olá,

Se você estiver utilizando Android, um detalhe importante que muitos estão "errando" é que você não pode trocar o GCMClientId que está no exemplo da integração com o Parse. Este ID é do próprio Parse.com e eles não dão opção de você utilizar seu próprio ID.

Veja se isso resolve seu problema e me retorne por favor.

Atenciosamente,

Arley

**Comment by somefakeuser** [comment]
Caramba! Era isso mesmo. Estou me sentindo um idiota, pois você colocou esse aviso no config.json e eu simplemente não vi até você mencionar.

Só mais uma coisa, os push estão chegando normalmente, mas sem som. Você já passou por isso?

**Comment by arleyandrada** [comment]
:-)

A definição de qual som será tocado quando receber a notificação é feita através do conteúdo enviado.

Veja que na documentação do meu módulo diz que você deve utilizar o atributo "sound" com o nome do arquivo de som que será executado ou o termo "default" que irá tocar o som padrão definido no celular.

O mesmo vale para vibração, luzes, título, mensagem, badge, etc...

Na interface web do Parse.com você pode informar que é um conteúdo JSON e utilizar algo como:

```
{
"alert" : "hello world!",
"sound" : "default"
}
```

Me retorne se der tudo certo ou se tiver alguma outra dificuldade.

**Comment by somefakeuser** [comment]
Maravilha! Muito obrigado mais uma vez.
Agora sim tudo tudo esta certinho e funcionando maravilhosamente bem.

Uma boa noite e bom final de semana para você.

Att,

**Comment by somefakeuser** [comment]
Arley,

Tudo bem?

Última dúvida que talvez você possa me ajudar, por favor. Você saberia me dizer como eu faço para unsubcribe de algum channel no parse? Encontrei alguns exemplos no google mas não estão funcionando.

Abs,

**Comment by arleyandrada** [comment]
Olá,

Sobre o "unsubscribe" de um "channel", a forma que considero a mais simples é você utilizar o método registerDevice que está disponível no meu exemplo.

Este método serve tanto para registrar o dispositivo, quanto para atualizar as informações do mesmo dispositivo, sendo possível assim se inscrever ou remover de um ou mais channels.

Qualquer dúvida me retorne.

Arley
