### ISSUE TITLE
iOS 9.3 PushClient not call event

### ISSUE THREAD

**Issue by kimjw0820** [arleyandrada/PushClient#130]
Hello!!

i use PushCall 1.14 and OneSignal service
titanium sdk 5.3.0.GA

Android is Good Work!
iOS 9.3 (PushClient.registerPush) API to don't call event.

but device tokens sendpush success.
Can you test?

Thank you!

**Comment by arleyandrada** [comment]
Have you copied the "workaround" code to the issue #17030 to your app?
Put these code lines at any place in your app.

```
//Workaround to Titanium Mobile issue #17030
//https://jira.appcelerator.org/browse/TIMOB-17030
if (OS_IOS) {
    var issue17030 = Ti.Network.registerForPushNotifications;
    var issue17030iOS8 = Ti.App.iOS.registerUserNotificationSettings;
}
```

Regards,

Arley

**Comment by arleyandrada** [comment]
Now, my pushclient module is free and open source!!! Have fun!
