### ISSUE TITLE
Clear Notification?

### ISSUE THREAD

**Issue by kerberosargos** [arleyandrada/PushClient#133]
Hi firstly thank you for developing this useable module.

is there any method for clear notification from notification bar? For example when app is turn from background to turn foreground, notification must be clear from notification bar.

**Comment by arleyandrada** [comment]
```
                    if (OS_ANDROID) {
                        Ti.Android.NotificationManager.cancelAll();
                    } else {
                        Ti.UI.iPhone.appBadge = 0;
                    }
```
