### ISSUE TITLE
Set smallIcon issue

### ISSUE THREAD

**Issue by kerberosargos** [arleyandrada/PushClient#135]
Hi I put small icon png file to "platform/android/res/drawable-hdpi/small_icon.png" folder and I pass param as below on my google payload. But small is not shown. Where is my fault?

remote.php

`'smallIcon' => 'small_icon.png'
`

**Comment by arleyandrada** [comment]
https://github.com/arleyandrada/PushClient/issues/116#issuecomment-178610269
