### ISSUE TITLE
Question: Onesignal PromptLocation iOS

### ISSUE THREAD

**Issue by MartinSRimsbo** [arleyandrada/PushClient#136]
Hi
I just started implementing this module in a project, and it works great with onesignal. I can't find a way to get the users "location radius" to work though. Is this something that could be done within this module? In the Onesignal native iOS API docs it is stated that all you need is call [self.oneSignal promptLocation]; and set the right permissions in your .plist and it will work.  I'm not very skilled in objective-c, so I thought asking would be faster than me fiddling around half blind ;)
Best

**Comment by arleyandrada** [comment]
No! It is not a feature from my module.
Push notifications don't handle location info.

But... you can code this and any other feature based on push notification.
You can send a "silent notification" with custom data that will tell to your app to get the user location and send it back to your server or to OneSignal server (through their api).
