### ISSUE TITLE
** BUILD FAILED ** [ERROR]

### ISSUE THREAD

**Issue by shadowhau** [arleyandrada/PushClient#137]
I have trouble implementing the module into my appcelerator project (iOS)

*\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Intermediates/<appname>.build/Debug-iphoneos/<appname>.build/Objects-normal/arm64/<appname> normal arm64
[ERROR] :  (1 failure)

**Comment by arleyandrada** [comment]
After some "googling"...

"Basically this problem occurs if your XCODE version is not the latest version!
Here is the catch, to install that version if you are on a mac you will need to upgrade (if you are not on it) to El Capitan.
Your application should then build as normal."

**Comment by arleyandrada** [comment]
Hi,

Check this issue:
https://github.com/arleyandrada/PushClient/issues/55

Regards,

Arley
