### ISSUE TITLE
In OneSignal what option I choose Android Native or Server Api ?

### ISSUE THREAD

**Issue by fukhaos** [arleyandrada/PushClient#139]
![captura de tela 2016-08-03 as 09 21 09](https://cloud.githubusercontent.com/assets/1226155/17365299/d32327a4-595b-11e6-9508-16c731f58522.png)

In OneSignal what option I choose Android Native or Server Api ?

**Comment by arleyandrada** [comment]
Choose the Android native, but don't really matter. This option is just to they try to help with client code, but all you need is the server api (same api to all client platforms).
