### ISSUE TITLE
Problem using Kinvey Push (maybe broken?)

### ISSUE THREAD

**Issue by nubu** [arleyandrada/PushClient#141]
Hey,

i've trying your module in a recent project, but the Push using Kinvey doesn't work correct. I think we have this problem earlier, maybe it is broken during several updates?

[INFO] :   ALERT: {"google.sent_time":1470735743625,"gcm":{"messageType":"gcm","handlerId":0},"payload":"{\"title\":\"TITLE\",\"smallIcon\":\"ic_stat_defaulticon_ios.png\",\"alert\":\"You have a new Message\",\"from\":\"Kinvey\",\"subject\":\"Welcome to BL\"}","from":"***_","collapse_key":"do_not_collapse","google.message_id":"**_***"}

The Payload contains strange string/Objects and i gues the module can't handle them correctly. Could you take a look on this? Would be awesome! :)

**Comment by arleyandrada** [comment]
There is no strange string/Objects.
I made an adjustment based on the information you sent.
Try the latest version:

https://github.com/arleyandrada/PushClient/blob/master/dist/br.com.arlsoft.pushclient-android-1.15.zip

https://github.com/arleyandrada/PushClient/blob/master/dist/br.com.arlsoft.pushclient-iphone-1.15.zip
