### ISSUE TITLE
Default sound not working on android

### ISSUE THREAD

**Issue by aniruddhasm** [arleyandrada/PushClient#145]
Hello,

I've integrated the module into my project. I am facing an issue with this module. Whenever I receive a notification I am not getting the `default` notification sound. Also I want to integrate the feature of sending the `big_picture` in the notification.
For your reference.
https://documentation.onesignal.com/docs/notifications-create-notification

Please help

**Comment by arleyandrada** [comment]
Custom or default sound:
https://github.com/arleyandrada/PushClient/issues/129#issuecomment-245157252

There is no "bigPicture" feature.
Code it and contribute to this open source repo. :-)
