### ISSUE TITLE
iOS Alert Style

### ISSUE THREAD

**Issue by Wingee** [arleyandrada/PushClient#149]
Is it possible to set the iOS alert style? It seems they can be changed in the Settings app to None, Banners or Alerts.
Is it possible to choose that the push notifications appear as Alerts instead of Banners by default?
Thanks

**Comment by arleyandrada** [comment]
With the iOS platform your app has no ability to act in relation to the style and behavior of the remote notification. It is defined by the payload sent to APNS and the user settings.

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

From your app, the only choice is which actions are available for each remote notification category.... and, ofcourse, listen to the callbacks.
