### ISSUE TITLE
License Problem

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#15]
Hi,

we have bought two seats of your Appcelerator Titanium Module PushClient. But if we start our App with the module on an Android Smartphone we get the following error:

```
"License violation detected. Unlicensed module(s) detected.  You must be a subscriber to use one or more of the modules included with this project.. Please contact Appcelerator Support.“
```

What is the problem? Please help!

Sincerely

**Comment by arleyandrada** [comment]
Hi,

Within the Titanium Marketplace you must assign each acquired seat to specific Titanium user / account.

Only the specified Titanium users (checked by through the logged user in Titanium Studio) can build and run the app without the "license violation".

Please check this and let me know if it works to you.

Regards,

P.S.: This "license violation check" it's not an feature from my module. It's fully controlled by Titanium Studio exactly the same way to any module.

 Arley

**Comment by somefakeuser** [comment]
Hi,

thank you for the fast answer.

But i have a seat for this module (i am assigned to the module within our company account). But it is not working.

Any other suggestions ?

Sincerely

**Comment by arleyandrada** [comment]
Hi Cetin,

All your developers run Titanium Studio logged with your company account?

Within your company account in purchased products from Appcelerator Marketplace you need to assign the seats to your developers account (same user logged at Titanium Studio).

Have you checked this?
I don't know another reason to fail the license module validation.

I wait your return.

Regards,

Arley

![unnamed](https://cloud.githubusercontent.com/assets/1809866/7508608/7dc80d0a-f459-11e4-85dc-09925d9465bc.png)

**Comment by somefakeuser** [comment]
It is really weird.

I have started a blank project and it is functioning!

But i have no solution why i can not integrate the module into my existing project.

Sincerely

**Comment by arleyandrada** [comment]
Hi,

Unfortunately as it is not a feature of my module, I can not help more than this instruction. 

I suggest that you contact the support team of Appcelerator Marketplace. 

Please get back to me if I can help you in something else. 
Sorry by can not help in this case.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi,

thank you very much. I will contact the support of Appcelerator for that issue.

Regards
