### ISSUE TITLE
Found incompatible Titanium Modules in Ti SDK 6.0.0.GA

### ISSUE THREAD

**Issue by csemrm** [arleyandrada/PushClient#156]
[ERROR] :  Found incompatible Titanium Modules:
[ERROR] :     id: br.com.arlsoft.pushclient	 version: 1.20	 platform: ios,iphone	 min sdk: 6.0.0.GA
[ERROR] :     id: br.com.arlsoft.pushclient	 version: 1.20	 platform: ios,iphone	 min sdk: 6.0.0.GA

[DEBUG] :  Looking for Titanium module id=br.com.arlsoft.pushclient version=1.20 platform=iphone deploy-type=development
[DEBUG] :  Found incompatible Titanium module id=br.com.arlsoft.pushclient version=1.20 platform=ios,iphone api-version=3 deploy-type=development
[DEBUG] :  Module br.com.arlsoft.pushclient has apiversion=3, but the selected SDK supports module apiversion=2 on platform=iphone
[DEBUG] :  Found incompatible Titanium module id=br.com.arlsoft.pushclient version=1.20 platform=ios,iphone api-version=3 deploy-type=development
[DEBUG] :  Module br.com.arlsoft.pushclient has apiversion=3, but the selected SDK supports module apiversion=2 on platform=iphone
[WARN] :   Could not find a valid Titanium module id=br.com.arlsoft.pushclient version=1.20 platform=iphone deploy-type=development

**Comment by fahad86** [comment]
@csemrm 1.20 is backwards incompatible and can only be used with Titanium SDK 6.0.0+. Use the older version 1.15. Should work pretty much the same.

**Comment by DouglasHennrich** [comment]
any news about this error? @arleyandrada

**Comment by ErikDohmen-xx** [comment]
@arleyandrada any ideas? Cause there are several other problems with restarting apps with earlier versions of Ti which makes that we need to use the 6.0 SDK. So we're actually caught in the middle now. If there is anything I can do to help, please let me know as students are waiting for an update of the uni app.

**Comment by arleyandrada** [comment]
I am unable to perform tests, however I am releasing the new version based on what was sent by @csemrm

My free developer account was rejected by the Appcelerator team and I don't want to pay for a new account.

https://github.com/arleyandrada/PushClient/blob/master/dist/br.com.arlsoft.pushclient-android-1.21.zip

**Comment by arleyandrada** [comment]
Waiting for tests from @ErikDohmen or @DouglasHennrich
Thanks!

**Comment by ErikDohmen-xx** [comment]
At a first glance all seems to work. I can register with one signal, get push notifications (if the app is closed). So both registering and receiving seems to work for android on 6.0.1 (which it didn't with the previous version).
@DouglasHennrich any tests on your end?

**Comment by DouglasHennrich** [comment]
I'm using a version compiled by @m1ga but I can't find it on Slack or on his repositories... but it works

**Comment by real-hive** [comment]
Thank you for fixing this!

**Comment by molsen-ee** [comment]
I'm getting this same error with PushClient 1.20 on iPhone.

```
Titanium SDK
  SDK Version                 = 6.0.1.GA
  SDK Path                    = /Users/molsen/Library/Application Support/Titanium/mobilesdk/osx/6.0.1.GA
  Target Platform             = iphone
[ERROR] :  Found incompatible Titanium Modules:
[ERROR] :     id: br.com.arlsoft.pushclient	 version: 1.20	 platform: ios,iphone	 min sdk: 6.0.0.GA
```
Has anyone been able to get past this issue on iPhone?

**Comment by molsen-ee** [comment]
I was able to fix the iPhone issue. Apparently the apiversion update from 2 to 3 was only for Android (based on the 6.0.0 SDK documentation). In the iphone manifest file I changed it back to "2", rebuilt the module and was able to build my app.
