### ISSUE TITLE
Support Rich Notifications

### ISSUE THREAD

**Issue by abdielou** [arleyandrada/PushClient#159]
Can this be done with Appcelerator 6.x and PushClient?

eg:
<img width="300" alt="android-rich-push-example" src="https://cloud.githubusercontent.com/assets/1036734/22351707/93586b10-e3ef-11e6-97b8-39dee8f1a2b9.png">
<img width="300" alt="ios-rich-push-example" src="https://cloud.githubusercontent.com/assets/1036734/22351722/9e2d69be-e3ef-11e6-9df7-f01927e6a51a.png">

**Comment by abdielou** [comment]
I would love if a largeIcon could be also set with iOS as it is done with Android

**Comment by rocket13011** [comment]
+1

**Comment by Rajveer123** [comment]
Hello Guys,

Same feature I have to implement so can any one help me in to that if you have already implemented that. I am using PushClient 1.21 module and 6.1.1.GA SDK.
