### ISSUE TITLE
More info about PushClient

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#16]
Hi,

I'm looking for a way to push data to Android and iOS... and I found PushClient.

Before buying the module I would like to know how I would push messages from my server to apps. Have you a technical documentation on the api of the server side ?

Moreover, like I understand the module process, my server would send directly messages to GCM and APN, is it right ?

Best regards

**Comment by arleyandrada** [comment]
Hi,

The technical updated documentation to the push service from Apple (APN) and Google (GCM) you must get straight from their websites, but I suggest you to find and use one of the many open source libraries according to your server technology.

What technology and programming language you use to develop server-side? Maybe I can help you with some tips.

.Net = https://github.com/arleyandrada/PushSharp
PHP = https://github.com/richsage/RMSPushNotificationsBundle
Node.js = https://github.com/Smile-SA/node-pushserver

Something about the push notifications:
- Both Apple and Google offers free and unlimited access to their push notification services;
- Many services like Push.com, Urban Airship and also Appcelerator Cloud Services offers simplified api and additional reports and control, but charges you by period, by payload volume, etc... Some of they very usefull; But they work like a proxy to the Apple and Google services;
- PushClient module works at client side; With my module you can easily handle the push notification from client side, within Titanium apps, regardless the platform (Android or iOS).

I hope I've been able to help.

Regards,

Arley Andrada Maria

**Comment by somefakeuser** [comment]
Hi Maria,

thank for your detailed reply.

Could you tell me if your module works when my app is in foreground, background, stopped, killed ?

What are the possibilities of interaction between the notification you display and my app ?

Regards

**Comment by arleyandrada** [comment]
Hi,

Yes, your app will be notified through the provided callbacks, identifying when the app is in foreground, background or when the user clicks on the alert / message at notification bar.

With iOS there is a "bug" and your app will not be notified when it is killed through the tasks window (only the alert / message is shown at notification bar). It's not a limitation of my module. With any other app states works fine.

With Android there is a limitation of my module, very similar to the iOS bug. If your app is not running in background (killed), I can't fire the background callback event yet, but the alert / message is shown at notification bar.

For most applications above facts are not problems. 

Any questions get back to me.

Regards,

Arley
