### ISSUE TITLE
Any suggest?

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#17]
Hi!

My goal is to develop a light-chat  using your “push module”; actually I’m  new using titanium studio.

I will appreciate if you have any suggest.

Kind regards.

**Comment by arleyandrada** [comment]
Hi,

As a tip, I suggest you to use Parse.com as a server side engine or build your own push notification server.

I have plans to release, in the next weeks, a new module to show and control an iOS 7 Message like conversation view.

Good luck!

Regards,

Arley

**Comment by somefakeuser** [comment]
Thaks you, I’ll considerate; however currently I’m using Amazon web services as push notification Server.

Regarsd and good luck to!

**Comment by somefakeuser** [comment]
Arley:

I’m starting a new Project (new alloy project) and try to include “var PushClient = require('br.com.arlsoft.pushclient'); “ as the example shows; but always a get a error, “[…] module not found”.

It obvious that I have not include into the the project correctly, what is the correct way to include the module ? I’m stuck!

Regards

**Comment by arleyandrada** [comment]
Hi,

Take a look at these links:
http://www.titaniumtips.com/files/modules_installation.php
http://docs.appcelerator.com/titanium/3.0/#!/guide/Using_a_Module

Or just unzip the downloaded module within your app "modules" folder.

[your-app] root folder
---> [modules] folder
-------> [android] folder
-----------> [br.com.arlsoft.pushclient] Android module folder
-------> [iphone] folder
-----------> [br.com.arlsoft.pushclient] iOS module folder

After install the module, open your app tiapp.xml file and configure / add the "br.com.arlsoft.pushclient" module to the module list.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks I have developed faster with you support.

One question more, what does mean this event (I find it into the example) ?

```
if (event.mode == PushClient.MODE_CLICK) {
                alert('Callback from Click:\n\n' + JSON.stringify(event.data));
                // Push data received when user clicks in notification message
}
```

Where or when a event like this is fired?

Thanks in advance

**Comment by arleyandrada** [comment]
Hi,

When your app is not in foreground, an alert / message is shown in notification bar. When the user clicks on this alert / message notification, your app will be started and this callback will be fired to identify this event with all payload data.

If are you receiving an foreground event instead of click event, you need to check if the PushClient's registerPush method is called at every app startup, regardless if it was called and registered the device before. It's reguired to code it at app.js or index.js (alloy main controller).

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

Does the “alert/ message notification” should be show in automatic way? I mean, do I have to setup something in order your module show the notification automatically ?

I have to Build the alert / message notification (no problem if I have to do), but is confused if I have to build or the module “pushclient” does the task.

In my App the RegistrerPush method, is only called once; if the registration is already done the app will not call registerPush method ever.

Regards

**Comment by arleyandrada** [comment]
Hi,

The PushClient handle and show the "alert / message notification" in automatic way, both for iOS and Android.

According to the sent payload push data, the "alert / message notification" will play a sound, will blink lights (Android), will show specific title (Android) and message info, will vibrate (Android), etc...

To fully work you must to call registerPush at every app startup.

There is no problem about to request an device registration multiple times (my module avoid the unnecessary connection to the APN and GCM).

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley:

OK  understood.

Please give a example of “PayLoad Data” in order to PushClient  show an “alert/ message notification”  and/or play a sound, blink lights, etc.

Regards

**Comment by arleyandrada** [comment]
Hi,

iOS with text, bagde and sound

```
{
"alert" : "Hello World!",
"badge" : 3,
"sound" : "bingbong.aiff"
}
```

Android with title, text, sound, vibrate and lights

```
{
"alert" : "Hello World!",
"title" : "PushClient",
"sound" : "default",
"vibrate" : true,
"lights" : true
}
```

Regards,

Arley

**Comment by somefakeuser** [comment]
Arley:

Thank you, I’m using Amazon Web Services Simple Notification Service; to send push notification. Here the payload received from AWS, I hope this help to improve your module.

Payload send to Android Device

```
{
"type":"PushClient_Callback",
"source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"PushClient_Callback":{}}},
"data":{"gcm":{"handlerId":0,"messageType":"gcm"},"collapse_key":"do_not_collapse","from":"931142733645","default":"Aqui_el_mensaje_Enviado_desde_AWS"},
"mode":3,
"bubbles":false,
"success":true,
"code":0,
"cancelBubble":false
}
```

I don’t have yet iOS’s device payload.

![unnamed 1](https://cloud.githubusercontent.com/assets/12264970/7508918/026f20d8-f460-11e4-93ed-175876b2540e.png)

**Comment by arleyandrada** [comment]
Hi,

With Amazon Web Services Simple Notification you can use the "use platform specific JSON message dictionaries" option to send exactly the required custom payload.

Heve you tried it before?

Thanks,

Arley
