### ISSUE TITLE
Google Play services not available

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#18]
I wonder if you could assist please?

I’m using your module and it’s working great for iOS, however whatever I do I cannot get it to work with Android, I keep getting the error message that “Google Play services not available” when I try to register. I have double checked the GCM Sender ID several times.

Thanks for your time.

**Comment by arleyandrada** [comment]
Hi,

Are you testing the PushClient module with a real Android device?
Is not possible to test it with Android emulator or with very old Android devices (without google play services).

Also you can check if your app is using another module or native functions which also require a google play services, like maps, payment, google account authentication... maybe there is an version conflict too.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks for the fast reply. I updated the Google Play app and it all started working!

Great module thank you!

**Comment by somefakeuser** [comment]
Hey there.

I managed to get your module working fine on iOS devices. However when I’m testing with new iOS 8 devices, no matter what I do they won’t register for push notifications? Is this something you already know about?

**Comment by arleyandrada** [comment]
Hi,

I have no tested my module with iOS 8 yet.

Which Titanium SDK and Titanium Studio versions are you building your app?
Which device are you using?

Did you see any alert, error or info at Titanium Studio console log?

I wait your response.

Regards,

Arley
