### ISSUE TITLE
How to keep Push Client module running in backgound even if the app is close by user

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#20]
Hi Arley:

I been develop an app pretty cool, of course using your Push Client module. Currently I deploy the app on Android device and every push send is received I mean, everything is cool. But if the app is closed (press the back button in android device, no pressing home button ) any push send is received no more.

I would expected that push client module, start a service and keep running even if the app is close, am I wrong?

What I have to do in  order to keep service push notification running in background to received push notification even if app is closed!

The push notification module is limited, to keep running in order to received push ?

Regards

**Comment by arleyandrada** [comment]
Hi,

Regardless of the app is in foreground, background or stopped / killed, your app have to receive the push notification.

When in foreground the callback event is fired and no alert is show in notification center;

When running in background the callback event is fired and an alert is show in notification center;

When the app is not running (stopped or killed) no callback is fired, but an alert is show in notification center;

When the user clicks one of the alert in notification center the app is started (if stopped or killed) or bring to foreground (if running in background) and a callback is fired too.

This is the spected behavior.

The main tip to get everything work is to call the registerPush method at every app startup (at app.js or index.js) regardless the device is already registered.

I'd like to know your app! :-)

Please let me know if it's ok or need some help.

Regards,

Arley
