### ISSUE TITLE
iOS 8.0

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#22]
Hi there! Thanks for the great module!

By the way, in iOS8
"enabledRemoteNotificationTypes is not supported in iOS 8.0 and later.”
"RegisterForRemoteNotificationTypes:. Is not supported in iOS 8.0 and later”
error message that comes out.

And it seems can not send notification to iOS8 device.

I use Parse.com. would not be a good solution?

sorry google translated. Thank you

**Comment by arleyandrada** [comment]
Hi,

My module still working fine in devices with iOS 8, but it's require do build with Titanium SDK from 3.2.1 to 3.3.0.

I'm working in a new version of my module to build successful with Titanium SDK 3.4.0.

Regards,

Arley
