### ISSUE TITLE
Help with PushClient

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#24]
Hello,

hope your well.

I bought your Titanium module this morning and wonder if you can help me with some tips to use it.

Looking your documentation and examples in iphone I won't understang where I need to place my cert id from Apple. I'm new in this topics, sorry if sounds dummy. 

Thanks for your help

**Comment by arleyandrada** [comment]
Hi,

You will use the certificate on your server and not in the app.

On the client side all you need is to use, in your Titanium App, the same App ID registered on Apple Developer website and enable the push notification service.

Some good reading:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW9

https://developer.apple.com/notifications/

http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1

https://parse.com/tutorials/ios-push-notifications

Regards,

Arley

**Comment by somefakeuser** [comment]
Thank you Arley

I would read all that asap. Any tips on how I can use your module with parse in android.

Again thank you for all the help.

**Comment by arleyandrada** [comment]
Within my module documentation you will find a parse.com sample integration.

**Comment by somefakeuser** [comment]
Hi Arley

I get this error in Adroid, can you help me to fix it. 

TIA

![unnamed 2](https://cloud.githubusercontent.com/assets/12264970/7509244/7f9d26f0-f464-11e4-823b-54e9af8c3a7f.png)

**Comment by arleyandrada** [comment]
Hi,

The problem you are facing on Android is related to the fact that the GCM requires the Google Play Services installed with a minimal version; Maybe your device is too old (can't be updated) or is just out of date; Try to check for updates with GooglePlay app.

For both iOS and Android is not possible to use Push Notifications with a emulated device.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thank you Arley

I thought in Android Virtual Device would work for testing. 

Is required to use a payment Google Cloud Platform for a production push through  Parse ???

Sorry if this not specific to your module. And thanks so much for share your knowledge.

**Comment by arleyandrada** [comment]
Hi,

No, it's not required to use GCP to be able to use GCM, regardless of use Parse or any other provider.

Regards,

Arley Andrada

**Comment by somefakeuser** [comment]
Hello Arley

Thank you very much for your help.

Now I can receive push form iOS and Android. 

How can I subscribe to a channel ???

TIA

**Comment by arleyandrada** [comment]
Hi,

Are you talking about Parse channels?

With my parse integration sample you can set an array of channels in the registerDevice method second argument. Try it.

Regards,

Arley

**Comment by somefakeuser** [comment]
Yes, I just saw it, sorry. I sent you another email with a serious error trying to register iOS. In Parse Console I delete iOS device row, maybe after deleted it can't be added again. I'm afraid to delete the Android device too but I need to test installation process in iOS and Android in Parse before trust in my code.

Please help
