### ISSUE TITLE
Sorry I can't subscribe correctly on iOS

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#27]
hi Arley

sorry to bother you again. 

I was subscribed to iOS using a GitHub Parse previous to buy you module. Then I realize  that Titanium.Network.registerForPushNotifications don´t work in Android and bought your module.

Now I'm trying to unify my code using only your module and after unregister iOS, I can´t get it subscribe again. The first alert return a successful registrationId, but after that an error happens when Parse.registerDevice is called.

Please help !!!! 

![unnamed 3](https://cloud.githubusercontent.com/assets/12264970/7509519/231e5d3c-f468-11e4-9192-4ffd164834b8.png)

![unnamed 4](https://cloud.githubusercontent.com/assets/12264970/7509520/29225f76-f468-11e4-874a-4ecb77b2e3c9.png)

**Comment by arleyandrada** [comment]
Hi,

My module is working properly and is registering the device successfully.

What may not be working properly is my Parse service integration example.

However I can try to help.

Regards,

Arley

**Comment by somefakeuser** [comment]
Yes Thanks,

Is very strange. 

This is the previous Parse.js I used to register an iphone. Maybe help.

**Comment by arleyandrada** [comment]
Hi,

I can't reproduce this problem here.

Have you changed the parse api request url?
POST https://api.parse.com/1/installations

Apparently the problem is in Titanium (it's a generic error, not specific to parse service). 

Which version of Titanium SDK are you using?

Try to log and check the request url before to call the httpclient send method.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley

Yes the URL is correct. As your module example. I use the same alloy code for iOS and Android, right ???

I'm using Titanium Studio 3.4.0.201409261227
and Titanium SDK 3.4.0

But this setup works with the Parse.js I sent to you.

I will keep trying and will let you know. If you get any news please let me know.

In worst case I will use bought methods for Android and IOS.

Thank you very much for your help.

Best regards

**Comment by arleyandrada** [comment]
Hi,

Yes, you can use the same alloy code for iOS and Android.

Related to iOS, there is some requirements:

My module works fine when published in iOS 8 devices, but there is a problem when build the app with Titanium SDK 3.4.0; It works fine with Titanium SDK from 3.2.1 to 3.3.0;

You need to copy and paste the few lines of code related to "Workaround to Titanium Mobile issue #17030" from my documentation to any place in your app.

One additional tip:

Call the "registerPush" method from my module every app startup (at alloy.js or index.js - main controller), regardless if the device is already registered before.

Please let me know if it works fine to you.

Regards,

Arley

**Comment by arleyandrada** [comment]
Also try cleaning your project and / or delete the folders "build" and "Resources" and compile the project again.

**Comment by somefakeuser** [comment]
Hi Alrey

Thanks you for the tips. 

This is my setup so you can confirm your module works with :
- Titanium SDK 3.4
- XCode 6.1

All code in alloy.js 

Thank you very much for your excellent module, support and patience. 

Best regards.

**Comment by arleyandrada** [comment]
Hi,

Titanium Studio 3.4.x = OK

Titanium SDK 3.4.0 = Incompatible
**\* use Titanium SDK from 3.2.1 to 3.3.0

XCode 6.1 = OK
iOS 8 = OK

Alloy = OK

Please also consider the information in my previous email.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley

Is there any chance to make PushClient compatible with Titanium SDK 3.4 

I need to work with iPhone 6 and iOs 8.x

Thanks in advance !!!

**Comment by arleyandrada** [comment]
Hi,

Good news!

I just released a new PushClient module version and it will be available at Appcelerator Marketplace in next days.

Changelog:
- Titanium SDK 3.4.0 compatibility with backward compatibility;
- Enabled to iOS 8 interactive notifications;
- Updated documentation and sample.

Have fun!

Regards,

Arley

**Comment by somefakeuser** [comment]
Woww Arley,

Thank you !!! I will try it asap.

You're the best.
