### ISSUE TITLE
Documentation for the iOS version

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#3]
Dear Arley,

Thanks for your message. I'm testing it right now. I've the Android part up and running, but the iOS version not. I try to get that working first. Maybe there's more documentation available for the iOS version, but I'll figure it out myself.

Thanks,

**Comment by somefakeuser** [comment]
Dear Maria,

I've bought a license. Do you have more information about the installation of the iOS module. This would help me a lot.

Thanks,

**Comment by arleyandrada** [comment]
Hi,

There's no special requirements related to my iOS Push module, but I know about some common problems:
- APN doesn't work on iOS Simulators. You need to deploy to real devices;
- Your Titanium App Id must be exactly the same as registered (iOS App ID) on Apple Developer (Certificates, Identifiers & Profiles / Identifiers / App IDs);
- Your iOS devices (UDID) must be registered on Apple Developer (Certificates, Identifiers & Profiles / Devices / All);
- Within your elective or your own Push Server you need to use the "APN Development iOS" certificate when deploying to iOS Devices through "Run" + "iOS Device" / "Your Device" on Titanium Studio;

That's all.

I wait your return.

**Comment by arleyandrada** [comment]
Hi,

In development build for iOS you need to use a documented workaround to an Titanium bug:

```
//Workaround to Titanium Mobile issue #17030
//https://jira.appcelerator.org/browse/TIMOB-17030
if (!OS_ANDROID) {
var issue17030 = Ti.Network.registerForPushNotifications;
}
```

Please let me know if everything is ok to your app.

Thanks,

Arley

**Comment by somefakeuser** [comment]
Dear Arley,

Thanks for you support. I've got everything working, so the module is working fine. 

Thanks,
