### ISSUE TITLE
PushClient v1.6 Background

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#32]
Hey Arley,

Since updating to v1.6, background notifications in android have stopped working. We didn't have a chance to try iOS notifications yet and so I can't comment on that right now.

We haven't changed a thing in our code yet. Only updated to v1.6.

Here is a log:
[ link removed ]

Lines 30-83 - app finishes closing.
Line 104 - module sets a notificationId property to a value of 8.

...then nothing happens. I'm not sure the background callback is being fired.

Any ideas?

Thanks,

**Comment by arleyandrada** [comment]
Hi,

With you app log I don't realize if the app is in background or is stopped or killed.

My PushClient module - all released versions - in Android can't fire the callback with MODE_BACKGROUND when the app is stopped or killed.

Have you checked this?

Regards,

Arley

**Comment by somefakeuser** [comment]
OK. I will double check this.

Just to confirm for iOS, we all we need to do for background is add this in to our tiapp.xml:

```
    <ios>
        <plist>
            <dict>
                <key>UIBackgroundModes</key>
                <array>
                    <string>fetch</string>
                    <string>remote-notification</string>
                </array>
```

Is this correct?

Thanks for all of your patience and support with us!

Cheers,

**Comment by arleyandrada** [comment]
Hi,

Also you must include the attribute "content-available" in your payload data.

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

Regards,

Arley

**Comment by somefakeuser** [comment]
OK. Thanks Arley. We'll try it out later today, but I'm sure it will work. Thanks for your support and this awesome module.

Cheers,
