### ISSUE TITLE
PushClient able to handle notifications to small groups?

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#33]
Hi there
I've been tasked with developing an Appcelerator app, with notification capabilities - and it loos like your PushClient module will do the trick.

I just see that all documentation talks about subscribing to a channel, and then, on the broadcast side, sending notifications to everyone.

So - is PushClient capable of being in a system with potentially many channels, and having many clients receiving from one or more of those channels?

if so - I'm going to start pestering my people here to buy PushClient.

Any information much appreciated!

Thanks

**Comment by arleyandrada** [comment]
Hi,

My PushClient module works regardless the existing channels or not.
Channels are features from providers like Parse which one is used in my sample code.

In this context, the simple answer is yes!

Fell free to ask me about any doubts.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley

Cool - I'm getting funds available as you're reading this.

In the meantime, I have many newbie questions like "what's a good way to store unique IDs on my system, so I can push notifications to users" and "what's a good intermediary (I'm assuming Parse)" and "how often does the app have to request tokens" and such.

If you can point me to any good sources of info - that would be great. I'm googling furiously at the moment, but find I'm hitting a lot of marketing material, or out of date stuff - so any leads you can give me would be great :)

Thanks a ton
I look forward to getting a copy of PushClient before the end of the week!
Have a good day

**Comment by arleyandrada** [comment]
Hi,

In my own projects I took the risk to create my own push notification provider.
However I suggest you to use some provider like Parse.com to avoid to have to deal with some push notification problems.

If you need to build your own server, maybe you want to use some of following open-source libraries:
.Net = https://github.com/arleyandrada/PushSharp
PHP = https://github.com/richsage/RMSPushNotificationsBundle
Node.js = https://github.com/Smile-SA/node-pushserver

Using your own server you can get every device registrationId by a web api call to your server.

Using some provider like Parse.com you need to read and follow their instructions.

With my module it's required to call the registerPush method at every app startup... and consequently obtain the device registration multiple times.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley
Thanks for that. Money should be on it's way to you now :)

We're arguing over something here at the moment: Would an app receive push notifications if it's been closed?

When it's in active, and when it's in the background - sure - we get notifications - but if the app has closed - say when closing it from the task manager - is there any way the device would receive the push notification?

Have a good one

**Comment by arleyandrada** [comment]
Hi,

Hope you buy multiple licenses of my module! :-)

Answering your questions...

My module handles the following callback modes:

MODE_FOREGROUND => Your app is active and in foreground when the push notification arrives; No sound, no message is showed in notification tray; You decide what to do with received payload data;

MODE_CLICK => Your app is not in foreground; Can be active or stopped; An message is showed in notification tray and/or with sound, vibration, lights, etc... according to your sent payload data; When the user clicks on the showed message in the notification tray, your app is started or putted in the foreground and this callback is fired with all payload data;

MODE_BACKGROUND (Android) => Fired when your app is active but is not in foreground; Does not prevent the MODE_CLICK event is triggered later when the user clicks on the showed message in the notification tray;

MODE_BACKGROUND (iOS) => Fired when your app is not in foreground (active or stopped) and you used the new "remote-notification" feature from iOS 7; Does not prevent the MODE_CLICK event is triggered later when the user clicks on the showed message in the notification tray.

When your app is not in foreground (active or stopped) an message always will be showed in notification tray for iOS or Android.

You can choose from some behaviors to the received notification through the sent / received payload data, according to my documentation and sample code: sound, vibrate, lights, title, message...

Unfortunately with iOS (even native) you can't customize the message showed in the notification tray; You are limited to choose the "alert" (text message), an optional "sound" and an optional "badge"; Always displayed with the same icon used in the application.

To iOS 8 (native) you could use a better interactivity with the notification, available at my latest module version.

In addition, for Android, if your app is stopped or was killed, NO callback is fired with BACKGROUND mode.

In addition, for iOS, if setting up the background mode and your app is stopped but NOT KILLED from app drawer, a callback IS fired with BACKGROUND mode.

If you app was killed, there is a known iOS bug that prevents the app to receive the notification in background.

More info about the "remote-notification" feature from iOS 7:
http://hayageek.com/ios-silent-push-notifications/

More info about the "interactive notification" feature from iOS 8:
http://www.appcelerator.com/blog/2014/09/new-in-sdk-3-4-ios-8-interactive-notifications/

Regards,

Arley

**Comment by somefakeuser** [comment]
:) I think one license per app I have to deliver is perfectly fair!

Okay, so I've followed the parse example, and get things going nicely, on Android at least (Don't have access to an iOS device yet - but I hear it's even easier to get that up and running)

Now - the people I'm integrating with want to use Microsoft Azure Notification hub.

They sent me this link : https://marketplace.appcelerator.com/apps/11522#!overview

... they didn't realise I tried this already and failed - all the compiling of my own modules etc. is just a bit crazy.

So - If I'm going to try and use Azure - I'm assuming this should be easy enough - we still use Apple and Google messaging infrastructure - just this time, instead of using parse to send messages, I'll be using Azure.

Do you have any advice at this stage? - can you think of anything I should pay particular attention to?

Again - thanks a ton - I hope to be up to speed and out of your hair shortly.

**Comment by arleyandrada** [comment]
Hi,

Thanks for your buy.

Unfortunately I have no experience with Azure Notification Hub.

Good luck and share with me your results.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley
Cool - will give it a go and let you know what happens.

In the meantime - how do you approach iOS vs Android typically? - do you even need to do switch/case between the two, or do you advocate separate code lines entirely for the two different systems?

Thanks

**Comment by arleyandrada** [comment]
Hi,

With my PushClient module you can use the same line codes to both platforms.

Related to the entire app source code, you can avoid lots of switch/case directives using "conditional code markup":
http://docs.appcelerator.com/titanium/3.0/#!/guide/Alloy_XML_Markup-section-35621528_AlloyXMLMarkup-ConditionalCode

Regards,

Arley
