### ISSUE TITLE
PushClient 1.6

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#34]
Hi Arley,

Hope you're doing well. I've noticed you've released a new version of PushClient. I'm glad to see you're keeping your modules up-to-date. I'm having a problem with the latest version though, it gives me a compilation error. I'm using Ti SDK 3.4.0 GA. Switching back to PushClient 1.5 lets me compile my app successfully. Please advise. Thank you.

**Comment by arleyandrada** [comment]
Here's more details:
```
Undefined symbols for architecture armv7:
[TRACE] :    "_OBJC_CLASS_$_TiAppiOSProxy", referenced from:
[TRACE] :        _OBJC_CLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
[TRACE] :       (maybe you meant: _OBJC_CLASS_$_TiAppiOSProxyHack)
[TRACE] :    "_OBJC_METACLASS_$_TiAppiOSProxy", referenced from:
[TRACE] :        _OBJC_METACLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
[TRACE] :       (maybe you meant: _OBJC_METACLASS_$_TiAppiOSProxyHack)
[TRACE] :  ld: symbol(s) not found for architecture armv7
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by somefakeuser** [comment]
Here's more details:

```
Undefined symbols for architecture armv7:
[TRACE] :    "_OBJC_CLASS_$_TiAppiOSProxy", referenced from:
[TRACE] :        _OBJC_CLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
[TRACE] :       (maybe you meant: _OBJC_CLASS_$_TiAppiOSProxyHack)
[TRACE] :    "_OBJC_METACLASS_$_TiAppiOSProxy", referenced from:
[TRACE] :        _OBJC_METACLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
[TRACE] :       (maybe you meant: _OBJC_METACLASS_$_TiAppiOSProxyHack)
[TRACE] :  ld: symbol(s) not found for architecture armv7
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by arleyandrada** [comment]
Hi,

I could not reproduce this error.

You've cleaned your project and deleted the old version of my module before to build your project again?

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

Yes, I've tried cleaning my project and removed the old version of your module, still getting the error.

**Comment by arleyandrada** [comment]
Hi,

Maybe you can help me to test building your project with the attached module special version.

Thanks,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Arley,

I've replaced the module with your updated version, still the same error comes up. It's worth mentioning that the project builds normally with iOS simulator as target but not with a real device (iPhone 5 with iOS 8.1, iPhone 4s with iOS 8.1).

**Comment by arleyandrada** [comment]
Hi,​

I really could not reproduce this compilation error and nobody else but you ask me about this error.

Maybe the problem is related to some conflict of my module with another modules or some feature used in your project.

If you can, share with me the source code of your entire project or a minimum version of it where the error still exists.

Thanks!

**Comment by somefakeuser** [comment]
Hi Arley,

Attached is a sample project with just your module and nothing else, yet still the same error occurs.

```
[TRACE] :  Undefined symbols for architecture armv7:
[TRACE] :    "_OBJC_CLASS_$_TiAppiOSProxy", referenced from:
[TRACE] :        _OBJC_CLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
[TRACE] :       (maybe you meant: _OBJC_CLASS_$_TiAppiOSProxyHack)
[TRACE] :    "_OBJC_METACLASS_$_TiAppiOSProxy", referenced from:
[TRACE] :        _OBJC_METACLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
[TRACE] :       (maybe you meant: _OBJC_METACLASS_$_TiAppiOSProxyHack)
[TRACE] :  ld: symbol(s) not found for architecture armv7
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  Ld build/Debug-iphoneos/PushTest.app/PushTest normal armv7
[ERROR] :  (1 failure)
```

[ attachment removed ]

**Comment by arleyandrada** [comment]
Hi,

I have found the problem.
It's related to a Titanium bug.
Just put the following code at anywhere in your project and built it again.
This workaround is documented and updated at my sample code.

```
//Workaround to Titanium Mobile issue #17030
//https://jira.appcelerator.org/browse/TIMOB-17030
if (!OS_ANDROID) {
    var issue17030 = Ti.Network.registerForPushNotifications;
    var issue17030iOS8 = Ti.App.iOS.registerUserNotificationSettings;
}
```

Thanks by your help!

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

Hope you're doing well. Just wanted to say thank you for helping me out. Your solution worked!
