### ISSUE TITLE
Pushclient Module

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#35]
Hello,

i bought your module to use it with parse.com.

Sorry but  I was not able to configure a simple solution with the provided example.

In the resource folder I have the app.js

and apse the parse folder with the 3 files.
alloy.js parse.js and config.json.

I entered the parse.com credentials to the config.json.
But these files does seem not to be required by app.js.

Please help me with a working example.
I would pay extra for it.

Best regards,

**Comment by arleyandrada** [comment]
Hi,

Within my module you can find a "example" folder with a "parse" subfolder.

Using an empty Alloy project, you should to move the "alloy.js" and "config.json" files to the "app" folder within your new project, and also should move the "parse.js" file to "app/lib" folder.

After that, entering the parse.com credentials to the config.json, everything must be working fine to Android (don't change the ParseGCMSenderId).

To get Parse.com working with APN (iOS) you need to follow a lot of instructions:
https://parse.com/tutorials/ios-push-notifications

Regards,

Arley
