### ISSUE TITLE
PushClient - notifications while android app not running

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#37]
Hi,

we are using PushClient to handle push notifications in our Titanium app. On Android we don't receive any notifications when the app is not running (background or foreground). Does PushClient support receiving notifications in this case?

Regards,

**Comment by arleyandrada** [comment]
"app is not running" in "foreground"?

PushClient supports receiving notifications in foreground, background... while is running, not running or else is killed.

Check your payload sent data. You need at least an "alert" attribute. Available attributes at my sample code.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi,

than you for your help. Adding alert attribute fixed it.

Regards,

**Comment by DanielBcnicode** [comment]
Hi,
do you have solved the problem???, I'm stopped for this problem.
