### ISSUE TITLE
push client install error

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#38]
Hello,
I have install your module, but when I run app in titanium I get this error:
Error: couldn't not find module: parse

thanks very much for your help,

**Comment by arleyandrada** [comment]
Apparently you are trying to use my sample code that demonstrates a possible integration with Parse.com provider.

This is not an error from my module but an error message generated by an incomplete use of my sample code.

If you wish to use the sample code with the Parse.com provider integration you must copy the file "parse.js" to the "app/lib" folder and also the file "config.json" to the folder "app" of your Alloy project and setup your Parse.com provider keys in file "config.json".

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks Arley, 

I have integrated parse with your lib,, can you tell me how can I show a alert with the text of the notification in the app when the user click on notificacion?, I have try this:

```
var eventCallback = function(event) {
    Ti.API.info('eventCallback:' + JSON.stringify(event));

    if (!event) {
        alert('Callback:\n\nInvalid callback');
        // Should never happen...
    } else if (event.mode == PushClient.MODE_FOREGROUND) {
        alert('Callback in Foreground:\n\n' + JSON.stringify(event.data));
        // Push data received with app in foreground
    } else if (event.mode == PushClient.MODE_CLICK) {
        alert('Callback from Click:1\n\n' + JSON.stringify(event.data));
        //here I want to show notification texto to user by alert, but I can not:           
        alert('Notification:'+JSON.stringify(event.data.alert));
    } 
```

Thanks

**Comment by arleyandrada** [comment]
Try this:

```
var payload = JSON.parse(event.data.data);
alert('Notification: ' + payload.alert);
```

Regards,

Arley
