### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#4]
Oi Arley, estava agora mesmo procurando vc no fórum do google :-)

Será que seu módulo vai trabalhar com http://codecanyon.net/item/send-mobile-push-notification-messages/6548533?WT.ac=search_item&WT.oss_phrase=push%20notification&WT.oss_rank=3&WT.z_author=smartiolabs ?

Estou iniciando com Titanium. Estivemos criando alguns apps pelo goodbarbe.com e como.com mas já não resolve.

Precisamos uma app bonita, simples, e integrada com o Wordpress pois estamos montando uns sistemas de gestão com marketing integrado e seria importantíssimo unir um app com possibilidade de enviar notificações pelo painel Wordpress.

Eu teria alguma dificuldade em usar seu módulo nesse sentido?

Você teria algum tempo para participar de um projeto?

**Comment by arleyandrada** [comment]
Olá,

Com meu módulo você irá conseguir receber as notificações push sem nenhum problema.
Não existem restrições ou limitações relacionadas com a origem do envio das notificações.

O projeto de vocês parece interessante.

Tenho tempo livre e interesse em trabalhar remotamente como freelancer.
Havendo a demanda, vocês poderiam descrever mais detalhes sobre o que precisariam para podermos discutir e negociar uma remuneração.

Aguardo retorno.

Atenciosamente,

Arley Andrada Maria
