### ISSUE TITLE
PushClient iOS

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#40]
Hello,

   I have bought PushClient iOS module from marketplace but i couldn't use it. Is there a tutorial how to use this ? I have look at the example but couldn't make it.

Thanks

**Comment by arleyandrada** [comment]
You don't need nothing more than what is in my module sample code.
It's really very simple.

What exactly is your problem?

It's not issues directly related to my module, but it is common to find problems related to the push notification provider or related to the registration of the app at the Apple or Google.

Which provider are you using?
Have you registered your app at Apple Developer site, enabled the push notification service and generated the required certificates?

Following are some useful links:

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

https://developer.apple.com/library/ios/technotes/tn2265/_index.html

https://parse.com/tutorials/ios-push-notifications
http://docs.aws.amazon.com/sns/latest/dg/mobile-push-apns.html

Regards,

Arley

**Comment by somefakeuser** [comment]
Hello,

   Thanks for the answer, first i have got some errors,
for example 
if (OS_IOS) { 

at this line 

system couldn't find what is OS_IOS

after that should i copy parse folder to my resources and change only two lines of it for to use this module ?

I am using Urbanairship but i will recode my apps to use parse.com

if i share my team viewer can you look at my app ?

**Comment by arleyandrada** [comment]
OS_IOS is available at any Titanium Alloy project.
Try to create a new Titanium Alloy project or try to define the OS_IOS variable as following:

```
var OS_IOS = Ti.Platform.osname === "iphone" || Ti.Platform.osname === "ipad";
```

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi arley, 

   Is this module for alloy ? I am not using alloy :(

**Comment by arleyandrada** [comment]
No, it's not for alloy.
My sample code was written using an alloy variable. That's all!

Regards,

Arley

**Comment by somefakeuser** [comment]
Ok arley,
  İ will try again this night and let you know tomorrow

Thanks a lot

**Comment by somefakeuser** [comment]
Hi Arley,

  I have tried and now app is getting registration id but when i want to test at parse.com, it is sayin no registered device.

  What do you think ?

Thanks

**Comment by arleyandrada** [comment]
Attached [Click Here](https://github.com/arleyandrada/PushClient) is a full working project integrated with Parse.com

You need to get the device registration ID and send it to Parse.com through theirs web api.
My sample code contains the code needed for this integration.

You need to register your app at Apple, enable push notification, generate the certificates, upload the certificates to Parse.com and copy the Parse.com web api key to your Titanium project (within config.json at my sample code).

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks a lot i Will try this and inform you 

Fyi: I have done everything from apple side because I know the process at that side before urbanairship.com. But I need to learn parse.com side . 

Thanks

**Comment by somefakeuser** [comment]
Hi arley as you can see I have this registration id, how can I Send this to parse.com? Should every user do this when they have download the app ? You send me an alloy project which I have don't know :( 

Thanks

**Comment by arleyandrada** [comment]
Try to open and read the source code.
The alloy project difference is related to UI... and there is almost no UI in my sample.

All you need is to get the parse.js file from my samples.
It is a commonjs library, compatible with classic or alloy Titanium projects.
Its exposes a Parse.com web api device registration method.

With no Alloy project you need to replace the Parse Keys configurations from other variables or constant.

Read the index.js file from my sample to check the simple integration of my module with the parse.js library.

I hope to be getting help.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hello,

   I have bought the android module too, but the same problem, i couldn't make it work :( it has registration id but when i check the parse.com there is no devices. If you have time can you help me about this. I can share my team viewer id and pass with . 

Thanks a lot

**Comment by arleyandrada** [comment]
You must use the GCM ID that is in my sample code. This is the Parse.com Google ID and they do not give you the option to use your own GCM ID.

That's all.

Regards,

Arley

**Comment by somefakeuser** [comment]
hi,

```
"Instructions" : "!!! do not change the ParseGCMSenderId config !!!",

        "ParseGCMSenderId": "1076345567071",
```

I didn't change this one, others are my ids, and i have put the gcmsender of mine, project id = gcmsenderid right ?

**Comment by arleyandrada** [comment]
"project id" = "gcmsenderid"

But to integrate your app with Parse.com you must to use theirs GCMSenderID.

The Parse's GCMSenderID is in my sample code within config.json as ParseGCMSenderID.

Forget your own GCMSenderID when integrating with Parse.com.

Regards,

Arley

**Comment by somefakeuser** [comment]
In my app.js

```
var registerOptions = {

    GCMSenderId : '1076345567071'

};
```

at the config.json

```
"Instructions" : "!!! do not change the ParseGCMSenderId config !!!",

        "ParseGCMSenderId": "1076345567071",
```

and i have used this id at parse.com Settings > Push
but at my android device, it has an alert registrationID 
but when i check the parse.com there is no devices ?

**Comment by arleyandrada** [comment]
Have you successfully registered the iOS app?
There's no difference at this point.

**Comment by somefakeuser** [comment]
I couldn't make the iOS too :(

**Comment by arleyandrada** [comment]
Maybe you can share your project with me.
I can fix it and send it back to you.

**Comment by somefakeuser** [comment]
I have attached the project 
Thanks a lot

[ attachment removed ]

**Comment by arleyandrada** [comment]
Attached is your app.

Edit the "config.js" file and set the "ParseApplicationId" and "ParseRESTApiKey" with your own keys. They are in Parse.com dashboard (app info).

That's all.

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Thanks a lot
I wil try and keep you updated

**Comment by arleyandrada** [comment]
It got bigger because that I enabled the compilation for iPhone and iPad.

**Comment by somefakeuser** [comment]
Thanks a lot ! :) I am using the module and i am getting Push notifications from Parse.com at my Android Device, i haven't test the iOS yet.
I have some little questions:

When i receive the push it is like json format what should i do change this line ?

```
            alert('Callback from Click:\n\n' + JSON.stringify(event.data));
```

There is no sound for push notifications.
How can i create channels and add this to the script .( If this is too complex forget it please )
Should i copy and paste the code for iOS , is this enough

Thanks a lot ! 
I am grateful

**Comment by arleyandrada** [comment]
1) "When i receive the push it is like json format what should i do change this line?"

Strange question!
Yes, like almost everything in a JavaScript code, the received and sent data is in JSON format.
Now you must remove the "alert" codes and implement what is required for your application. I can't help with this...

2) "There is no sound for push notifications."

You should send push notifications with specific attributes as documented in my sample code.
Example: { "alert" : "Hello world!", "sound" : "default", "vibrate" : true }

```
// Categories (for iOS 8):
// Equivalent to Ti.App.iOS.createUserNotificationCategory and Ti.App.iOS.createUserNotificationAction
// https://wiki.appcelerator.org/display/guides2/iOS+Interactive+Notifications

// Notification properties:
// "alert" (String) to text message - or "text" to Android
// "sound" (String) to sound file to play - "default" to Android default sound
// "badge" (Int) to iOS badge count indicator
// "content-available" (Int) to iOS background notification
// -->> Requires set remote-notification UIBackgroundModes in tiapp.xml
// "notificationId" (Int) to Android notification identification
// "title" (String) to override Android notification title - default app name
// "ticker" (String) to override Android ticker message - default alert message
// "vibrate" (Boolean) to use default Android device vibration
// "lights" (Boolean) to use default Android device lights
// "smallIcon" (String) set small icon to Android notification from assets
// "largeIcon" (String) set large icon to Android notification from local file or url
// "category" (String) to iOS 8 interactive notification
```

3) "How can i create channels and add this to the script .( If this is too complex forget it please )"

Yes!
With the provided "parse web api" library you can set the channels when registering the device. It is the second argument of registerDevice method.
You can also read the Parse Web API documentation and change my sample code.

4) "Should i copy and paste the code for iOS , is this enough"

Yes, of course!
You can also use the same app project to both platforms.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

You can see my comments in red below.
You should send push notifications with specific attributes as documented in my sample code.
// Which file can you write me please ?

Thanks a lot

**Comment by arleyandrada** [comment]
Try this:

```
var payload = (typeof event.data.data === "object") ? event.data.data : JSON.parse(event.data.data);
alert('Notification: ' + payload.alert);
```

"The JSON.stringify() method converts a value to JSON, optionally replacing values if a replacer function is specified, or optionally including only the specified properties if a replacer array is specified."

"The JSON.parse() method parses a string as JSON, optionally transforming the value produced by parsing."

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
http://www.json.org/

You must use these "short codes" within your sent payload (JSON) data from Parse.com.
Some "short codes" are platform specific.

```
{
"alert" : "Hello world!",
"sound" : "default",
"vibrate" : true,
"badge" : 1,
"content-available" : 1,
"notificationId" : 1,
"title" : "Some title",
"ticker" : "Some ticker",
"vibrate" : true,
"lights" : true,
....
...
..
}
```

The documentation about of these "short codes" is available, in addition of this e-mail, also in the sample .js files (alloy.js, index.js or app.js).

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

  Thank you very much ! I am grateful .
  Have a good night 

Cheers !

**Comment by somefakeuser** [comment]
Hi Arley,

   Maybe you have faced this error before ?

  I am using your Parse Module and Ti.Map module, but it is giving an error about the jar file .

```
[ERROR] : Conflicting jar files detected: [ERROR] :
[ERROR] : The following modules have different "google-play-services.jar" files [ERROR] :
[ERROR] : You can either select a version of these modules where the conflicting jar file is the same or you [ERROR] : can try copying the jar file from one module's "lib" folder to the other module's "lib" folder.
```

  I have changed the Ti.Map version 2.1.4, 2.1.3, 2.1.2, 2.1.1 but didn't work

  So i have copy and paste the ti.map jar file and paste to your modules lib folder --> Doesn't work
       i have copy and paste the your module jar file to ti.map module lib folder --> It is saying Unlicensed module(s) detected. I have generate a new uuidgen with terminal and clean my project , run again same problem.

   I have google it but no useful documents.

Thanks

**Comment by arleyandrada** [comment]
Use the attached updated module.

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Hi Arley,

  It has the same problem again.

```
[ERROR] :  Conflicting jar files detected:

[ERROR] :  

[ERROR] :  The following modules have different "google-play-services.jar" files

[ERROR] :     br.com.arlsoft.pushclient   (version 1.7) (hash=a9b753b4c63719e24d0022e341c57b2e)

[ERROR] :     ti.map                      (version 2.1.4) (hash=d424e23c8c3cc78af897bef37f9a62c7)

[ERROR] :  

[ERROR] :  You can either select a version of these modules where the conflicting jar file is the same or you

[ERROR] :  can try copying the jar file from one module's "lib" folder to the other module's "lib" folder.

[ERROR] Application Installer abnormal process termination. Process exit value was 1
```

   Both files are the same you attached ? They are 1.7 version and when i unzip the files , both files are same.

Thanks

**Comment by arleyandrada** [comment]
Are you building with Titanium SDK 3.4?

**Comment by somefakeuser** [comment]
Yes i am using 3.4.1GA

if you are ok you connect my comp via Teamviewer

Teamviewer id: xxxxxxx
Password: xxxxxx

Thanks

**Comment by arleyandrada** [comment]
Attached is your app project again, but now with my updated module inside.
I also added the Ti.Map module to test the Google Play Services version compatibility problem.
This latest PushClient module version was build exactly to fix this problem.

Before built it again, please clean your project.

[ attachment removed ]

**Comment by somefakeuser** [comment]
It has the same problem again :(

**Comment by arleyandrada** [comment]
The license problem is related to my PushClient module and not to Ti.Map.
I sent to you a "multi platform" version of my module, but you buy a module to each platform.

Try to use the attached module.

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Hi Arley, 

   I have fixed the issue like below, 

   I have copied both modules to my application folder , after this I have changed the udids at manifest.xml s for each module and Tiapp.xml at application . Both udids are the same so no problem at all.

Is this ok for you ? 

Thanks a lot for your help

**Comment by arleyandrada** [comment]
Changing the manifest is a good workaround, but you will get the same problem after each module update. Changing the manifest you are "cheating" the module license verification.

Please, try to use the modules sent in my previous e-mail or use the attached project (with updated modules inside).

My module works fine with ti.map android version 2.2.2 or later.
Attached is a ti.map module version 2.2.2 if needed.

If do you want to use the ti.map 2.1.4 (latest stable version), you can copy the "google-play-services.jar" file from ti.map module lib folder to PushClient module lib folder.

From: ~/Library/Application Support/Titanium/modules/android/ti.map/2.1.4/lib
To: <your-app-folder>/modules/android/br.com.arlsoft.pushclient/1.7/lib

ti.map latest master version:
https://github.com/appcelerator-modules/ti.map/tree/master/android/dist

I hope this will solve all the current problems.
Please let me know if is everything OK now.

Related to the "native google maps", did you read the available official documentation?
http://docs.appcelerator.com/titanium/3.0/#!/guide/Google_Maps_v2_for_Android
http://docs.appcelerator.com/titanium/3.0/#!/api/Modules.Map

Regards,

Arley

[ attachment removed ]

**Comment by arleyandrada** [comment]
I'm working in a fix to the Google Play Services version conflict. Plans to be released today.

Regards,

Arley
