### ISSUE TITLE
PushClient: How do I set the badge number on iOS and Android?

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#43]
The module seem to work quite well for me in conjunction with Parse, but how do I set the badge number on iOS and Android? It will increment the badge, but I can't seem to reset it?

Thanks,

**Comment by arleyandrada** [comment]
To set the badge on iOS or Android you need to send a payload data with an "badge" counter attribute.

```
{ "alert" : "Hello World!", "badge" : 10 }
```

Unfortunately most of Android devices does not shows the "badge" counter over the app icon... or shows an badge counter related to the total unread notifications.

To clean or set the badge counter (only to iOS) within your app:

```
Ti.UI.iPhone.appBadge = 0;
```

http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.iPhone-property-appBadge

Regards,

Arley
