### ISSUE TITLE
PushClient iOS - Appcelerator Marketplace

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#45]
Hello!

I have a question about your iOS module, works with Parse at 100% percent? can i use it with my own server and php? and most important, will be updates for new Xcode versions and titanium versions? thanks in advance!

**Comment by arleyandrada** [comment]
Yes, is it working fine (100%) with Parse.com for many users / projects.

Yes, my module is compatible with latest Titanium, Android and iOS versions and I keep it updated.

Regards,

Arley
