### ISSUE TITLE
PushClient - help

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#51]
Hi,

We were asked by a client to modify his mobile application done with Titanium.
He is using Urban Airship for push notifications but he now wants Parse so we bought your module to do this.

2 things :

1-      I tried to make it work in a “Test” application using Alloy framework, following your example but I always get : 
Message: Uncaught Error: Requested module not found: parse
What do I need to do to make this work?

2-      Also, the existing app is not using the Alloy framework… 
Can you tell me what has to be changed to make it work?

I’m really stuck with this and I would appreciate some help please.

Thank you!

**Comment by arleyandrada** [comment]
The error message displayed is related to lack of parse.js file (contained in my module example) in the lib folder (default folder for application-specific library code in Alloy project). Copy or move it to that folder. Pay attention to config.json file which must be in your root app folder and updated with your Parse keys.

My module is not dependent of Alloy. You can make some few changes to my sample code to get it to work in classic Titanium projects:
- Move and rename the sample code files to classic Titanium folders;
- Review and change the require directive to fix the file paths;
- Define the OS_ANDROID variable (in alloy.js file) with any classic Titanium library variable or change to anything like "Ti.Platform.osname == 'android'".

That's all.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thank you, it’s all working fine now!
