### ISSUE TITLE
Appcelerator Marketplace - Problems with Push Client

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#54]
Hi,

I just purchased the PushClient in Appcelerator Marketplace and tried to setup Push Notifications for iOS and Android.

iOS works fine but I have some issues with Android GCM. I use the example app.js and don’t use parse or something like that, just direct connections to Googles GCM Service.

The App successfully registers to the Google GCM Service, I get my token, everything is fine. When I send a push notification via HTTP Server directly to GCM, I can see the successful receiving of the notifications in the callback-functions. So receiving of notifications works, otherwise I would not see them in the callback logs, right?

But I cannot see the notifications on the device. When the app is not running, nothing happens. No notifications are displayed by the system, nothing happens.

Any help is highly appreciated because I have no clue what I’m doing wrong.

Thanks & best regards,

**Comment by arleyandrada** [comment]
You are almost there...

Now you just need to send a valid JSON message, with one or more specific attributes (read about valid options in my sample code). Something like this:

```
{ "alert" : "Hello World!", "vibrate" : true }
```

That's all.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

great, thanks a lot, it works nearly perfectly now!! Maybe I need one last litte hint: I now successfully receive the notifications, but due to multiple installations and deinstallations of the same app I now registered multiple IDs to gcm which causes the App to receive multiple notifications that all look the same, see log attached:

```
[INFO] :   eventCallback:{"type":"PushClient_Callback","source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"PushClient_Success":{},"PushClient_Error":{},"PushClient_Callback":{}}},"mode":3,"data":{"gcm":{"messageType":"gcm","handlerId":0},"alert":"Hello","message":"TestMessage","from":"768030288981","collapse_key":"do_not_collapse","vibrate":"true"},"bubbles":false,"success":true,"code":0,"cancelBubble":false}
[INFO] :   eventCallback:{"type":"PushClient_Callback","source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"PushClient_Success":{},"PushClient_Error":{},"PushClient_Callback":{}}},"mode":3,"data":{"gcm":{"messageType":"gcm","handlerId":0},"alert":"Hello","message":"TestMessage","from":"768030288981","collapse_key":"do_not_collapse","vibrate":"true"},"bubbles":false,"success":true,"code":0,"cancelBubble":false}
[INFO] :   eventCallback:{"type":"PushClient_Callback","source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"PushClient_Success":{},"PushClient_Error":{},"PushClient_Callback":{}}},"mode":3,"data":{"gcm":{"messageType":"gcm","handlerId":0},"alert":"Hello","message":"TestMessage","from":"768030288981","collapse_key":"do_not_collapse","vibrate":"true"},"bubbles":false,"success":true,"code":0,"cancelBubble":false}
[INFO] :   eventCallback:{"type":"PushClient_Callback","source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"PushClient_Success":{},"PushClient_Error":{},"PushClient_Callback":{}}},"mode":3,"data":{"gcm":{"messageType":"gcm","handlerId":0},"alert":"Hello","message":"TestMessage","from":"768030288981","collapse_key":"do_not_collapse","vibrate":"true"},"bubbles":false,"success":true,"code":0,"cancelBubble":false}
[
```

This causes the system to show four identical notifications every time I receive „one“. This differs from my testing devices, some devices only receive one notification, some receive more.

Thanks again for your valuable suppport & best regards,

**Comment by arleyandrada** [comment]
There should be no problem to perform the device registration multiple times (multiple registrationId). The last entry is the only one that works.

Rechek if your server / provider is not sending the payload multiple times to your device.... or if you have registered the PushClient event multiple times (addEventListener).

Regards,

P.S.: Sorry for my delayed response.

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

the server sends 1 Message to 4 registrationIDs and all 4 IDs are handled by the device. "The last entry is the only one that works“ is not what happens here (although it should). gcm sends the same message to 4 different registrationIDs and all 4 messages are received. When I uninstall the app and install it again, I receive 5 notifications. And 6 and 7… tried it multiple times on multiple devices. Every new install makes the app receive one more notification.

Any ideas what can be the issue?

Best,

**Comment by arleyandrada** [comment]
I will try to reproduce this behavior to be able to help you, but maybe you can try to send your payload data with an "notificationId" (Int).

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi!

Thanks, and yes, I can/will do that. This behaviour should not happen, I know that. Thanks a lot that you try to reproduce that, I will send you the logs with the notificationID so you can see that the app receives multiple messages for different IDs. Strange behaviour, anyway...

Best,

**Comment by somefakeuser** [comment]
Hi Arley,

thanks for your support, I think I can fix the problem. I use HTTP Interface for gcm ( https://developer.android.com/google/gcm/http.html ). When using this interface, gcm accepts „old“ registrationIDs but responds with a JSON telling me that the registrationID has changed and gives me the latest one. Although Google knows that the ID is no longer valid, they transport it to the „new“ ID - multiple times when multiple „old“ identifiers exist.
But I can update the database and remove the old IDs by myself.

Maybe this information is helpful to you for further support requests from other customers.

Best,

```
Sent to APA91bH6P0E3CtZ8uqtPb4iqjkWFttL7AWhZ421KB-TKrb9DSAKkk70DwMcUXEH0nydN54NPfGf2jjq_0H-G8twC6YHFx-9If8hDneQoyIi_sxDSIoebdaH4v_tu1E6geIiBdGufXtkeghk_juUsktjgzCe5mlLIR2dELNk2BP5KNKzsBXnzFZg - GCM Result  {"multicast_id":4970517024894768138,"success":1,"failure":0,"canonical_ids":1,"results":[{"registration_id":"APA91bGOwLXCMdrGZuK9yYyABXqjSTSFyTSYvjfB0DacyqqTFMK2xIQk38A4rzcDZYyIJKFf-8hQ0WS-CXOYFWnT4zmBvBb0WELdi_ptsWEzPm0tmO4StGet1IpFbIbCYuyRVEYy6yiI0h2ZCFPXj8mTtOLkvj0cn1h8k7roJi9gdRkRHC0YNbs","message_id":"0:1422022892352310%2537efc8f9fd7ecd"}]}

Sent to APA91bEgt3ogRm7Od031a-hqNTwk1wWRV56gw7tsobQEgqeXX4Y3Txrp2ST8_Mdc8io_kP39dowQjx_PIYvw4tDS0g4f10UnX02KM2ha_L_lQf5Wmi6Rdk1TXU26thcFde6udLC-PLKqV1JN-GJgiQHOs16UhXVxI69CKyTDbuv3enQIwVpwc9A - GCM Result  {"multicast_id":7413218316084401218,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1422022892459239%2537efc8f9fd7ecd"}]}

Sent to APA91bG8eG-7udstedyuw3Y3wMLFT5QFWMpFyA2Ww2QK7SUZVnuUvKRQfvFiRaAgqdQiwthgfaemymiE3Vk87EPT38WGcUomL-gYEzMXr9JOXmsRPG6xMVlm_HG2tPTPlyWLPoQ5dC9PdKLP36g7tSko9B4iTdQ9u_NBzl8CgZR3nwS3UUgNql8 - GCM Result  {"multicast_id":8518816292263890199,"success":1,"failure":0,"canonical_ids":1,"results":[{"registration_id":"APA91bGOwLXCMdrGZuK9yYyABXqjSTSFyTSYvjfB0DacyqqTFMK2xIQk38A4rzcDZYyIJKFf-8hQ0WS-CXOYFWnT4zmBvBb0WELdi_ptsWEzPm0tmO4StGet1IpFbIbCYuyRVEYy6yiI0h2ZCFPXj8mTtOLkvj0cn1h8k7roJi9gdRkRHC0YNbs","message_id":"0:1422022892544821%2537efc8f9fd7ecd"}]}

Sent to APA91bGPurqAm18LwVGmYhj4vvsG7OzzFsSn4h_pNeaRtqQ4WPzyTQEt-Uoqshz8q06PPhhQ7WPDvrscGbja7m1J7ug-O0xrWIsSljGosuleJ4soPCi4Xn0DoBVd_mu-rwMXlRp6LMKDHDOBEl_HKXXWElb0gaq_niJkx9DUq_Qlk0pea-oTcpM - GCM Result  {"multicast_id":5642667807655531643,"success":1,"failure":0,"canonical_ids":1,"results":[{"registration_id":"APA91bGOwLXCMdrGZuK9yYyABXqjSTSFyTSYvjfB0DacyqqTFMK2xIQk38A4rzcDZYyIJKFf-8hQ0WS-CXOYFWnT4zmBvBb0WELdi_ptsWEzPm0tmO4StGet1IpFbIbCYuyRVEYy6yiI0h2ZCFPXj8mTtOLkvj0cn1h8k7roJi9gdRkRHC0YNbs","message_id":"0:1422022892638383%2537efc8f9fd7ecd"}]}

Sent to APA91bGOwLXCMdrGZuK9yYyABXqjSTSFyTSYvjfB0DacyqqTFMK2xIQk38A4rzcDZYyIJKFf-8hQ0WS-CXOYFWnT4zmBvBb0WELdi_ptsWEzPm0tmO4StGet1IpFbIbCYuyRVEYy6yiI0h2ZCFPXj8mTtOLkvj0cn1h8k7roJi9gdRkRHC0YNbs - GCM Result  {"multicast_id":7124530322287139741,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1422022892726254%2537efc8f9fd7ecd"}]}

Sent to APA91bGaIC6M47XSyfJfZ-3oqeJewEDiI7RMWoOIudwQFS1WedrrnyaVs-eLbdeqb5QgIWGqqROcN-_ihcaZF7vOUjvs7oBHJWxyDWVDFv6CyOYWDZ90tx8x8qH_KBQPnDaudxShR50Ty3nPJdHpnUW16qO5UlY5hJsniwyVQJI5YaFGRu8pqDY - GCM Result  {"multicast_id":5509924532813905154,"success":1,"failure":0,"canonical_ids":1,"results":[{"registration_id":"APA91bGZb8TmBV7XVlHzUQRl54UxwMlGeYlAwPL0DDkwjlVshYPSEt0dSs_TS4TrVgQsz9WcZNyZqnCFCGjvOrnuS4e-SspQHS1XA8lvX7CxnsU5Md4ymrrDipdtGET1CDfHzogkTQpyKfsOtjq1SSXEhPKl3cDH7kmozZVbnsl_l7JULdFsMgk","message_id":"0:1422022892833874%2537efc8f9fd7ecd"}]}

Sent to APA91bHtqPPP4ebjMB_uBwWNuoPUd7g8vuR_fHYr_SM7fvcq5NsKcd-06SROBJ3G9qMJkZbr4kOYKk_51DVSZbq8_n5NILz0lzpaiUbJT-c1O6eZLMLO8rKugMRHGmgHQeRglyrcFZrpwBSC9K2jdxA4ZhQ8_l-ZqqTX08_dnRKnQgOsKXvhSBE - GCM Result  {"multicast_id":8152577526403232191,"success":1,"failure":0,"canonical_ids":1,"results":[{"registration_id":"APA91bGZb8TmBV7XVlHzUQRl54UxwMlGeYlAwPL0DDkwjlVshYPSEt0dSs_TS4TrVgQsz9WcZNyZqnCFCGjvOrnuS4e-SspQHS1XA8lvX7CxnsU5Md4ymrrDipdtGET1CDfHzogkTQpyKfsOtjq1SSXEhPKl3cDH7kmozZVbnsl_l7JULdFsMgk","message_id":"0:1422022892933723%2537efc8f9fd7ecd"}]}
```

**Comment by arleyandrada** [comment]
Good news!
Thanks a lot.
Regards,
Arley
