### ISSUE TITLE
Build failed for iOS

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#55]
Hi Arley,

your module works great on Android.
I started testing on iOS and can't build the App (see log.txt)

Your Testapp works on iOS but my App gets the build error.
I don't know what difference could result in this problem.
Any idea?

I am using Xcode 6.1 and Ti 3.5.0 for iPhone 5s with iOS 8.1.
I tested with 1.5, 1.6 and 1.7 of your module.

Regards

**Comment by arleyandrada** [comment]
Have you copied the "workaround" code to the issue #17030 to your app?
Put these code lines at any place in your app.

```
//Workaround to Titanium Mobile issue #17030
//https://jira.appcelerator.org/browse/TIMOB-17030
if (OS_IOS) {
    var issue17030 = Ti.Network.registerForPushNotifications;
    var issue17030iOS8 = Ti.App.iOS.registerUserNotificationSettings;
}
```

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

thanks, that was it!

Regards
