### ISSUE TITLE
Re: PushClient

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#56]
Hi Arley,

I have had another small issue with the module.

I have an app that was working perfectly as a development app.
When I installed it on test devices there was a pop-up asking if they wanted push notifications.
It communicated with my server and I could send them.

But when it was released on the app store, when the user opens it they are never asked if they wanted push notifications.

Is this a problem you have seen before ?

Is it most likely certificate related ?

Any help would be appreciated.

Cheers

**Comment by arleyandrada** [comment]
Take a look at the following links:

"Get back “Allow Push Notifications” dialog after it was dismissed once...".

"By default, your server can send silent/hidden/badgeless notifications to your app without permission from the user...".

https://bhaveshdhaduk.wordpress.com/2014/07/03/ios-apns-get-back-allow-push-notifications-dialog-after-it-was-dismissed-once-apns-permissions-popup/

https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG42

http://www.joshwright.com/tips/ios-8-push-notification-registration

https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html

Regards,

Arley
