### ISSUE TITLE
Questions: PushClient

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#58]
Hello,

I have questions about your script
1. It is compatible with the latest Titanium SDK?
2. Always Compatible with Android and iOS also with 8?
3. We have used parse.com like push services?
4. Can we use acs of Appcelerator?

I am very interested in your script

thank you

**Comment by arleyandrada** [comment]
1. It is compatible with the latest Titanium SDK?
   YES
2. Always Compatible with Android and iOS also with 8?
   YES
3. We have used parse.com like push services?
   YES, it is compatible with many push service providers.
   Used and approved by many users, with different providers.
4. Can we use acs of Appcelerator?
   YES, but as is with any provider, you need to code the device registration integration.
   My module comes with integration sample code to Parse provider.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thank you for your quick response

your source is ready for acs titanium?

fourniseur pushwoosh as it will also work?

thank you

**Comment by somefakeuser** [comment]
hello my application is made with titanium but not with the method allow, your module work? easy to set up? we have used parse.com? thank you

**Comment by arleyandrada** [comment]
There is no Alloy requirement for my module.

If you copied my sample code to a Titanium Classic project, maybe you can have problem with the missed "OS_ANDROID" constant... which you must change to something like "Ti.Platform.osname == 'android'".

Related to previous e-mail:

I have no tested with ACS Titanium or Pushwoosh, but my module was encoded in a generic way that allows it to work well with any provider. If you have any problems, please call me back.

That's all.

Regards,

Arley

**Comment by somefakeuser** [comment]
hello, I am currently using acs tiranium, here is my code app.js, I can easily replaced the old code by the web? there is a lot of code has changed, many file? thank you

[ link removed ]

**Comment by arleyandrada** [comment]
I don't understand your question.

"by the web"?

"many files"? Which files are you talking about?

Have you read my module documentation provided at Appcelerator Marketplace?

Regards,

Arley

**Comment by somefakeuser** [comment]
I'm watching, I'm not in front of my pc. my question is will that there are many file has changed? thank you :)

**Comment by somefakeuser** [comment]
Hello, I have Bought your script.

But I'm a lost can, I need your help please.

I would like to use the script with parse.com

can you tell me how to set it?

I have added this line in my app.js page

var PushClient = require ('br.com.arlsoft.pushclient');

Then I have configured the config.json file?

then make a parse.js include the file in my app.js file?

Ti.include ('parse parse.js');

like this

have a simple example to sent me, please?

thank you

**Comment by arleyandrada** [comment]
Whitin my module you will find a example.

**Comment by arleyandrada** [comment]
Copy the alloy.js and config.json to the app folder (Titanium Alloy Project) and the parse.js to the app/lib folder.

Change the config.json with your Parse.com keys.

**Comment by somefakeuser** [comment]
I do not use an allow project.

How can I ensure that it works directly in my application?

My app runs on android and ios

here is my app.js file attachment

thank you for helping me
please

[ attachment removed ]

**Comment by somefakeuser** [comment]
I want to know one thing,
if I work on a normal application without alloy.

I always need the parse.js file?

I have to put the same level as the app.js file?

I think for a normal app you just change this line for android ->

file parse.js

```
    var params = {
            //'deviceType' : (OS_ANDROID) ? 'android' : 'ios',
            'deviceType' : (Ti.Platform.osname == 'android) ? 'android' : 'ios',
            'deviceToken' : registrationId,
            'installationId' : installationId,
            'channels' : channels
        };

    //if (OS_ANDROID) {
    if (Ti.Platform.osname == 'android) {
        params['pushType'] = 'gcm';
    }
```

We still need to change the config.json file?

Thank you

**Comment by arleyandrada** [comment]
Looks like you are on the right track!

Yes, you can replace the "OS_ANDROID" Alloy global constant by "Ti.Platform.osname == 'android'".

The "parse.js" file is an regular CommonJS module provided as a sample Parse.com provider integration.
https://wiki.appcelerator.org/display/guides2/CommonJS+Modules+in+Titanium

Whithout the "parse.js" file you need to write your own Parse.com integration.

By the way, without an Alloy project you need to replace the "Alloy.CFG.xxx" by your own constant/variables.

Let me know if it's everything OK right now.

Regards,

Arley

**Comment by somefakeuser** [comment]
ok I'll try to do that. To better understand can you tell me if I can use another provider for push? that your module based exclusively parse.com? my English is bad, I'm from belgium. we can use other provider? free? thank you for helping me to understand ...

**Comment by arleyandrada** [comment]
Yes, you can use ANY push provider.

My native module (PushClient) handles the client side events in a generic way, with a similar behavior to iOS and Android.

However, to integrate to any push provider you need to write or customize your own integration code... that will always be something similar to my "parse.js" file (very simple code).

I have news that of others users of my module have successfully integrated theirs apps with different providers like Baidu Cloud Push, Kinvey, Amazon SNS or own providers.

Unfortunately I do not provide support for write that integration.
You can easily find info about how to write your integration, through some provider api.

Regards,

P.S.: I'm from Brazil. Sorry by my english too! :-)

Arley

**Comment by somefakeuser** [comment]
ok I'll try with parse.com if I can not get you help me? but I'll try anyway thank you, cool the country brazil football

**Comment by arleyandrada** [comment]
Go on!
I will try to help you with any doubts.

**Comment by somefakeuser** [comment]
Hello I think I have almost everything configured but I still have a problem in terms of exports, the last of parse.js file

exports.registerDevice = RegisterDevice;

can you tell me how to handle this problem?

attached my app.js + capture file

Thanks you

![ios simulator screen shot 24 janv 2015 22 29 18](https://cloud.githubusercontent.com/assets/12264970/7530426/82b55abe-f51e-11e4-8f68-2ad9a1d86723.png)

[ attachment removed ]

**Comment by arleyandrada** [comment]
Do you understand how a CommonJS module works?

Read more about this in the link sent previously:
http://docs.appcelerator.com/titanium/3.0/#!/guide/CommonJS_Modules_in_Titanium

To load / use a CommonJS module you need to use the "request" directive instead of "include".

Regards,

Arley

**Comment by somefakeuser** [comment]
it is good that?

var parse = require('parse/parse');

because it works without error

I think everything is ok,

but when I log in parse.com

I see no registered user
So I do not know envoy push

Do you have any idea?

Thanks

![img_0163](https://cloud.githubusercontent.com/assets/12264970/7530434/b29d3efe-f51e-11e4-8e48-956e042d3fc4.PNG)
![screenshot_2015-01-24-23-28-24](https://cloud.githubusercontent.com/assets/12264970/7530435/b4c551b2-f51e-11e4-839a-8cb8c7e9cf38.png)

**Comment by arleyandrada** [comment]
You need to use the "parse" module!
Take a look at my example code... from where did you get the "parse.js" file.

After to get the registrationId (from event success callback), you need to send it to Parse.com through the "parse" integration module.

```
    parse.registerDevice(event.registrationId, [], function(error, response) {
        if (error) {
            alert('Parse API Error:\n\n' + JSON.stringify(response));
        } else {
            alert('Parse API Success:\n\n' + JSON.stringify(response));
        }
    });
```

Try it.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hello my friend, I did my best, but I can not set.

I am sending you my two files, when you have time can you please controlled?

I also configured as you requested parse.js file with my data

but it does not work

(I tried this code: it works, https://parse.com/questions/push-notifications-when-using-titanium 
but not with your code)

:(

[ attachment removed ]

**Comment by arleyandrada** [comment]
Take a look at the attached files.
Try it.

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Thank you very much for your help

Registration for iOS and Android works very well.

I tried to send a push, it works on iOS, android but I do not get push.

GCMSenderId the code is good, it's the same I use in and push acs acs works with titanium.

There is an additional adjustements for android?

Thank you so much for everything

**Comment by arleyandrada** [comment]
Try to use the GCMSenderID provided in config.json file from original sample code.

**Comment by somefakeuser** [comment]
Thank you it works fine now for iOS and Android (y)

I have a few questions if you do not mind
- When I run the application it still gives me the message after successfully parse api + info, and the message id registraton.

How can I hide the message for the first time and do not always displayed when I run the application.
- To ios I have been in the settings to enable manuelement push, this is normal? we do not know on by default? See image attachments
- For the GCM Sender Id we use the id by default, the the  1076345567071 ?
  we can not use our? or maybe my id code was not properly configured

Thank you thank you thank you for all

![step_1](https://cloud.githubusercontent.com/assets/12264970/7530453/035f6150-f51f-11e4-90fa-17c91a59b86e.PNG)
![step_2](https://cloud.githubusercontent.com/assets/12264970/7530454/05040786-f51f-11e4-8177-641ddb7ab28c.PNG)

**Comment by arleyandrada** [comment]
The alert messages is for debug purpose.
It is required to keep the device registration at every app start, even if the device is already registered.

iOS users can change the behavior or even disable push notifications from the device settings. You can't avoid or control this feature.

You can try to use your GCMSenderId, but you need to set up it correctly in Parse.com... make some tries.

Tip: to better control the push notification use the payload in JSON format... something like { "alert" : "Hello World!", "vibrate" : true, "badge" : 2 }

Regards,

Arley

**Comment by somefakeuser** [comment]
Ok for everything
- For the registration I put in "Ti.API.info" example ->

```
var eventSuccess = function(event) {
    //alert('Registration Id : ' + event.registrationId);
    Ti.API.info('Registration Id : ' + event.registrationId);

    parse.registerDevice(event.registrationId, [], function(error, response) {
        if (error) {
            //alert('Parse API Error:\n\n' + JSON.stringify(response));
            Ti.API.info('Parse API Error:\n\n' + JSON.stringify(response));
        } else {
            //alert('Parse API Success:\n\n' + JSON.stringify(response));
            Ti.API.info('Parse API Success:\n\n' + JSON.stringify(response));
        }
    });
};
```

Normally it's good?
- To GCM Sender Id, I'll try 
- Thank you for the tip, but it is possible to preview the message without json?
  See image attachments, it is not easy to understand

normally I need to change this line, but I can not get decoded just message

```
alert('Callback from Click : ' + JSON.stringify(event.data));
```

Thanks

![alert_msg](https://cloud.githubusercontent.com/assets/12264970/7530464/32d2a4ba-f51f-11e4-9e13-3bbe9157650d.jpg)

**Comment by arleyandrada** [comment]
Ti.API.info is ok!

To securely get the "decoded" JSON payload, try to use something like:

```
var payload = (typeof event.data.data === "object") ? event.data.data : JSON.parse(event.data.data);
alert('Notification: ' + payload.alert);
```

No, it's not possible to preview JSON messages at Parse.com.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hello thank you for your help,

Concretely can also comment the lines following code right?

Because when you received the push we see the message, you click and it opens the application.

I think this is the objective of push

what do you think?

```
/*var eventCallback = function(event) {
    if (event.mode == PushClient.MODE_FOREGROUND) {
        alert('Callback in Foreground : ' + JSON.stringify(event.data));
    } else if (event.mode == PushClient.MODE_CLICK) {
        alert('Callback from Click : ' + JSON.stringify(event.data));
    } else if (event.mode == PushClient.MODE_BACKGROUND) {
        PushClient.endBackgroundHandler(event.data.handlerId);
        alert('Callback from Silent:nn' + JSON.stringify(event.data));
    } else if (event.mode == PushClient.MODE_ACTION) {
        alert('Callback from Action:nn' + event.category + 'n' + event.identifier + 'nn' + JSON.stringify(event.data));
    }
};*/


//PushClient.addEventListener(PushClient.EVENT_CALLBACK, eventCallback);
```

I still would like to ask a question
if you do not mind, you even have really helped me when
thank you again.

My last question is this:

How we can handle channels?

for example

the channel: home will open the application
news channel news.js open the page of the application, it is possible to manage that?

if so what is the code displayed news.js

Do you have any idea?

Thank you so much for everything

**Comment by arleyandrada** [comment]
The usefulness of push notification goes beyond to open your app.
You can send data from your server to your app users.

Related to Parse.com channels, you can set the user channels with the second argument (array of string) of registerDevice method (in your app)... and from Parse.com you will be able to filter the destinations by one or more channels.

You need to listen to callback event to code the required behaviors according to received push notification data.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi,
Can tell you another example, for date, for sending given to the user?
For each different channel, I have set the callback different right?

Thanks

**Comment by arleyandrada** [comment]
From now on you need to plan (by yourself) your app behavior, choose the channels to subscribe, define your server (Parse.com) payload data and code the callback event in your app to get things done!

It's not my business... it's not a feature from my module... and I do not provide support for this.

Sorry!

Regards,

Arley

**Comment by somefakeuser** [comment]
I understand that you are providing support only for your modules

I want to know you extra support for this work
to parse, optimized according to my needs?

if so what is your price?
thank you

**Comment by arleyandrada** [comment]
OK. I'm available for some frelancer work.

According to the complexity, feasibility and size of your needs I will give my price.
Please, try to write your needs and the expected app behavior.

Regards,

Arley
