### ISSUE TITLE
titanium-push client module- enquiry

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#59]
Hi,

I would like to purchase your push client module for appcelerator. Before that I would like to know whether your module is able to de following operations.
- Receive push notifications on app quit state
- Notification click redirection to custom window

Thanks & Regards

**Comment by arleyandrada** [comment]
Yes, you can receive push notifications when your app is not in foreground and also when your app is not open (not started).

Yes, you can listen for a callback event fired when user click on the received notification and code any app behavior.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi arley,
Can you provide a sample code for the redirection purpose when app is not in background. It is mandatory to do custom redirections. I cannot find any documentation before purchasing of module.
Thanks in advance.

Thanks & Regards

**Comment by arleyandrada** [comment]
My module do not deal with any redirections... therefore you will not find any documentation related to this. My module only allows you to code it.

You need to use the callback event, check the event arguments and code any behavior to your app. Something like that:

```
var eventCallback = function(event) {

    var dataContainer = (OS_ANDROID) ? event.data.data : event.data;
    var payload = (typeof dataContainer === "object") ? dataContainer : JSON.parse(dataContainer);

    if (event.mode == PushClient.MODE_CLICK) {
        if (payload.customDataSendFromServer == "show-about") {
            if (check-if-about-window-is-not-visible) {
                aboutWin.open();
            }
        }
    }

};
PushClient.addEventListener(PushClient.EVENT_CALLBACK, eventCallback);
```

Regards,

Arley
