### ISSUE TITLE
status notification

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#6]
can you give me an example to create status notification with your module and resume when click at it.

Thanks,

**Comment by arleyandrada** [comment]
Hi,

My PushClient module helps you to deal with device registration and easily handle received push notifications within your Titanium app, both for iOS (APN) and Android (GCM) devices, but like any app that use push notification, you need to send push notifications from an server.

You can build your own push notification server (there is lots of free libraries) or use some broker like Parse.com.

My module comes with an sample code.

Please let me know if you need anything else.

Regards,

Arley Maria
