### ISSUE TITLE
How to send a notification from a server

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#64]
i just buy your module for Titanium , it shows up the registerID, but i can not find my device in the appcelerator back panel . can you let me know where to send a notification message ? thx

**Comment by arleyandrada** [comment]
My native module (PushClient) handles the client side events in a generic way, with a similar behavior to iOS and Android.

However, to integrate to any push provider you need to write or customize your own integration code... that will always be something similar to my "parse.js" file (very simple code).

I have news that of others users of my module have successfully integrated theirs apps with different providers like Baidu Cloud Push, Kinvey, Amazon SNS or own providers.

Unfortunately I do not provide support to code this integration.
You can easily find info about how to write your integration, through some provider api.

My module comes only with sample integration to Parse.com provider.

Regards,

Arley
