### ISSUE TITLE
PushClient Android question

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#66]
Greetings,

I'm in the process of implementing your "PushClient" module in an Alloy app for both Android and iOS. So far the Android implementation has been going smooth however I have a question regarding push notifications received when the app is not running.

Based on your example app, the PushClient.MODE_BACKGROUND is being triggered if I open the app then hit the "home" key before sending a push notification.

If I open the app then hit "back" (to close the app) the background notifications will not be received. If a user restarts their device and the app has not been launched it will also not receive the push notifications.

On iOS this works properly, the notifications show up even if the app is not running.

Do you have an example app that will work as described?

Thank you,

**Comment by arleyandrada** [comment]
Unfortunately for Android the MODE_BACKGROUND callback is not fired when the app is closed, not running or was killed.

With the available Titanium SDK is not possible to wake up the app, keep it in background and reach the Javascript callback handler, unless if it is running before.

However, regardless if the app is closed, not running or was killed, when a push notification is received (not in foreground), a notification alert (with the provided text message) must be shown in the Android notification bar... then, when the user clicks on the notification alert, the app is started in foreground and the MODE_CLICK callback is fired.

To get the notification alert it is required to provide at least the "alert" or "text" attributes in your JSON payload data.

```
{
"alert" : "Hello world!",
"content_available" : 1,
"badge" : 10,
"largeIcon" : "http://rocketdock.com/images/screenshots/supermario.png",
"vibrate" : true
}
```

Hope this helps.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thank you for the response and explanation. I was able to get the Android alerts working as desired.
