### ISSUE TITLE
Push client for android on titanium sdk

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#67]
Hi,
Before buying from market place I just wanted test once with my android  application.
Let me know u can pass on trail version.

**Comment by arleyandrada** [comment]
There is no trail version.
Sorry.

**Comment by somefakeuser** [comment]
Then how to make sure it works..? 
Atleast few days I will try & confirm.

**Comment by arleyandrada** [comment]
There is no technical way to provide secure trial version.
Sorry again.

Read about push notifications, read my module documentation, read my sample code provided together with the module documentation, read all the positive reviews and make your decision.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi 
I didn't find any reviews.. Please can you point me.

**Comment by arleyandrada** [comment]
Read the module reviews from the following link:
https://marketplace.appcelerator.com/apps/10615?restoreSearch=true#!reviews

Regards,

Arley
