### ISSUE TITLE
Problems Getting started on Android

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#68]
Hello I am having issues getting started with your module. I bought the module that is meant for both platforms but I am trying with android right now. I updated all my android packages and it still doesn’t work. It will however build on my coworkers machine but all of our environment is seemingly the same. The error happens when it try to register the device.

Here is the error:

```
[WARN]  W/System.err: java.lang.NoClassDefFoundError: com.google.android.gms.common.GooglePlayServicesUtil
[WARN]  W/System.err:   at br.com.arlsoft.pushclient.PushClientModule.checkGooglePlayServiceAndRegister(PushClientModule.java:186)
[WARN]  W/System.err:   at br.com.arlsoft.pushclient.PushClientModule.registerPush(PushClientModule.java:178)
[WARN]  W/System.err:   at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[WARN]  W/System.err:   at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[WARN]  W/System.err:   at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:299)
[WARN]  W/System.err:   at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
[WARN]  W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN]  W/System.err:   at android.os.Looper.loop(Looper.java:130)
[WARN]  W/System.err:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] TiExceptionHandler: (main) [2322,2322] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [1,2323] - In pusher.js:1,69
[ERROR] TiExceptionHandler: (main) [0,2323] - Message: Uncaught Error: com.google.android.gms.common.GooglePlayServicesUtil
[ERROR] TiExceptionHandler: (main) [0,2323] - Source: ventListener(PushClient.EVENT_ERROR,this._registerError),PushClient.registerPu
[ERROR] V8Exception: Exception occurred at pusher.js:1: Uncaught Error: com.google.android.gms.common.GooglePlayServicesUtil
```

The weird thing is that we have a google anylitics that uses the google player services jar as well and it works fine but this still doesn’t work. if you have any advice I would be really grateful.

**Comment by arleyandrada** [comment]
Is it common to get this error when there is a conflicted GooglePlayServices version.
My module use / works with GooglePlayServices version 6.1.71.

Check another modules and also the Titanium SDK build version.
Don't try to change the GooglePlayServices lib from my module.

Please tell me if could make it work.
Maybe you want to share your project with me... or a minimal version of it.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hey Arley,

I figured it out, the problem was that I had multiple versions of Android SDK Build Tools installed. I uninstalled all but newest one on a hunch after your email and it worked! Thanks for your help!
