### ISSUE TITLE
instructions for android

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#7]
I'm testing it today, what do I need to do to activate it there were no instructions for android

**Comment by arleyandrada** [comment]
Hi,

Within downloaded PushClient module there is an small documentation and an sample code to iOS and Android (same code to both platforms).

There is also an extra sample code to integrate PushClient module with Parse.com.

You need to build your own server (there is a lot of samples in the Internet) or use an server / service like Parse.com to sent push notifications to your device.

Regards,

Arley
