### ISSUE TITLE
Quick question about foreground notifications

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#70]
Hey Arley, 

I promise this will be the last time I bug you but is there anyway to treat foreground notifications like backgrwound notifications? I mean that they show up in the notification manager (the top bar) and you are able to click on them later.

Thanks for your help and your library is amazing. I am already up and running and sending out push notifications!

**Comment by arleyandrada** [comment]
There is an unreleased version of my module (attached) which allows you to show an local notification when receive a push notification in foreground, but is available only to Android.

To iOS you need to use the Titanium SDK and to create a local notification.

```
var eventCallback = function(event) {
    ...
    if (event.mode == PushClient.MODE_FOREGROUND) {
        if (OS_ANDROID) {
            PushClient.showLocalNotification(event.data);
        } else {
            //Local notification with Titanium SDK...
        }
    }
    ...
};
```

Any doubt return me.
Have fun! :-)

Regards,

Arley

[ attachment removed ]

**Comment by somefakeuser** [comment]
Awesome! You made it so that the click event already uses my click event as well. Just Awesome!
