### ISSUE TITLE
help

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#71]
Hi,
I tried to use your pushclient module on Appcellerator Titanium.
The push notification works fine when my app is in foreground but doesn't work in background mode.

Which are the permission that I must insert in my tiapp.xml?

thanks a lot

**Comment by arleyandrada** [comment]
Check your payload sent data.
You need at least an "alert" attribute.
Available attributes at my sample code.

```
{
"alert" : "Hello World!!"
}
```

Regards,

Arley
