### ISSUE TITLE
PushClient module: "License violation detected" error

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#72]
Hi Arley,

I hope you're doing well. I purchased your module a few months ago. I
tried to use it just now and I got the license violation error. This
happens with both version 1.6 and version 1.7. What should I do?

I am compiling on Linux with Studio. This is with Titanium SDK 3.5.0.GA,
though the same thing happens with 3.3.0.GA (at least with version 1.7).
I'm running Android 4.4.2 on a Samsung SGH-I337.

Another quick question for you. We have to register the phone each time on
startup. But can the phone still receive push notifications even when the
app is killed?

Thanks!

**Comment by arleyandrada** [comment]
Both in iOS or Android, when a push notification is arrived with app "not in foreground" and with at least an "alert attribute", an message is always automatically showed in notification tray. When user clicks on that message, your app is started and a CLICK callback is fired, regardless if it is stopped, killed or running.

With Android, when the app is in background (not stopped or killed) an BACKGROUND callback is fired with all payload data.

With iOS, if you enable the iOS 7 "background notification" feature, when the app is in background or stopped (not killed) an BACKGROUND callback is fired with all payload data. When your app is killed the iOS 7 "background notification" feature do not work (existing known bug).
http://hayageek.com/ios-silent-push-notifications/

Both in iOS or Android, when the app is in foreground, an FOREGROUND callback is fired and none message is showed in notification tray.

TIP: It's required to call the registerPush method from my module at every app start, regardless if the device is already registered.

Related to the "license violation", please check if you are using Titanium Studio logged with user "dom@restadoapp.com", reckeck your account settings (assign products) at Appcelerator Marketplace and remove all references and versions of my module from your computer and download it again.

![xxxx](https://cloud.githubusercontent.com/assets/1809866/7530870/8fb8489a-f526-11e4-9058-0162e8257ca4.png)

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks so much for the helpful response Arley!

I think there is something wrong with the appcelerator marketplace. The same license issue happens with the iamyellow gcm module, which is a free module. This seems to be a common issue with marketplace modules.

I followed the steps in the last comment in this thread and it seems to have solved the issue.

Take care,
