### ISSUE TITLE
PushClient Module Titanum 3.5.1

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#74]
Hey,

did you test the module with the latest Titanium SDK? For me it doesn't work at the moment. (When receiving a push, the app crashes)

Any idea/hint?

Best,

**Comment by arleyandrada** [comment]
Yes, it is working fine with Titanium SDK 3.5.1.GA both for iOS and Android.

Maybe I can help you if you can share your error log with me.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hey,

thansk for the quick answer.

Sad thing:
There is no error-log. - The app just crashes... :/ If i remove the module from tiapp.xml than the app wouldn't crash. (But at the moment and even after hours of trying out things, i can't say 100% the module is the source.)

Even more strange, if it's working for you without any problem.

Best,
