### ISSUE TITLE
Question about pricing

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#75]
Hello, I'm Sebastian Ziegler

I'm writing to you because I've a doubt about your module PushClient in appcelerator marketplace.

If I buy the module, can I use it unlimited times after I bought it or I've to buy it each time I need to use it on an app?

Cheers

**Comment by arleyandrada** [comment]
The license for my PushClient module is "per user" (pay once), for unlimited projects, without usage fee.

You can buy one or more licenses and, using the Appcelerator Marketplace, assign each license to any Titanium user account.

Only licensed users can build, publish or debug projects containing my PushClient module.

Regards,

Arley
