### ISSUE TITLE
license modules: Push

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#76]
Hello,
nearly two months ago you helped me push for the installation of modules

I would like to work on a second application
and I would like yet used your Push Module

can you tell me if I have to take a second license? on the market for Appcelerator?

my app is the same as the old one, except that I'm going to change the home page
can you tell me the procedure to do?

Thanks

**Comment by arleyandrada** [comment]
The license for my PushClient module is "per user" (pay once), for unlimited projects, without usage fee.

You can build, debug and publish how many projects you want with the same license, if you continue to work with the same user / developer account.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi,
it's really nice
You're a cool (y)

I did the duplication of the app
it works very well

good luck for the future
