### ISSUE TITLE
Purchased titanium PushClient and have a question...

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#78]
Hello!

I purchased your PushClient just now (using account bxgrant@yahoo.com).  Looks great.

In version 1.7 it says, " Amazon SNS provider compatibility"

I'm going to be using Amazon SNS.  In what way does your client support Amazon SNS?

Do you have any additional sample apps or doc beyond what came in the download?

Do you have a sample of using Amazon SNS or anything else that would help me?

Thanks so much!

**Comment by arleyandrada** [comment]
The notified "Amazon SNS provider compatibility" and others providers, are related to the correct payload handling within my PushClient module.

Unfortunately my module integration sample is exclusive to Parse.com provider.

My compatibility tests came through help from other module users.

I suggest that you read and make the necessary adjustments in the Parse.com integration sample (provided with my module) to adapt it to the Amazon SNS.

Regards,

Arley
