### ISSUE TITLE
PushClient Android

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#79]
Hi.
I'm using you module with iOS and everything works perfect, but now I'm trying to use ti with Android and I don't receive any pushes!? Do I need to add something to the tiapp.xml?
I use it with Parse and there I can see the device is registered, but I don't get the pushes on the device when I'm testing.

Any toughts?
Best Regards,

**Comment by arleyandrada** [comment]
No. You do not need to change the tiapp.xml.

Please, recheck if you are using the correct CGMSenderId and if it is accordance to the Parse.com settings.

By default, with Parse.com to Android, you need to use theirs GCMSenderId (1076345567071) and not your own.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi and thank you for the reply.
I just figured out like you said about the sender id. Seems to be working now.

Again, thank you for good support !

Best Regards,

**Comment by arleyandrada** [comment]
Try to change your payload data from "message" to "alert" or "text".

Sorry by the delay in response.

Regards,

Arley
```
// Notification properties:
// "alert" (String) to text message - or "text" to Android
// "sound" (String) to sound file to play - "default" to Android default sound
// "badge" (Int) to iOS badge count indicator
// "content-available" (Int) to iOS background notification
// -->> Requires set remote-notification UIBackgroundModes in tiapp.xml
// "notificationId" (Int) to Android notification identification
// "title" (String) to override Android notification title - default app name
// "ticker" (String) to override Android ticker message - default alert message
// "vibrate" (Boolean) to use default Android device vibration
// "lights" (Boolean) to use default Android device lights
// "smallIcon" (String) set small icon to Android notification from assets
// "largeIcon" (String) set large icon to Android notification from local file or url
// "category" (String) to iOS 8 interactive notification
```
