### ISSUE TITLE
how to install the modules

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#8]
So I've downloaded the module, got the documentation but I need to know how to install the modules.

Another thing I don't understand is if i need to configure all the files on parse folder that the example folder has.

**Comment by arleyandrada** [comment]
Hi,

To install an module you need to follow this instructions:
http://docs.appcelerator.com/titanium/3.0/#!/guide/Using_a_Module

The parse folder is an example how to connect my module with Parse.com services.
In this example with Parse.com service you should configure only the items "ParseGCMSenderId", "ParseApplicationId" and "ParseRESTApiKey" whitin config.js file.

If you are planning to use your own push notification server you can follow the sample from root app.js file.

Please let me know if you need anything else.

Regards,

Arley

**Comment by somefakeuser** [comment]
Do I need Parse or my own push notification server to manage notifications? I thought I could manage them from appelerator.

**Comment by arleyandrada** [comment]
If you have plans to use ACS you need to use an module provided from Appcelerator.
Check it out : http://docs.appcelerator.com/cloud/latest/#!/api/PushNotifications

**Comment by arleyandrada** [comment]
I have created my PushClient module to help people to use push notification services (like me) without to pay for any services that charges you by devices, by app or by sent messages. The iOS (APN) and Android (GCM) are 100% free services.
