### ISSUE TITLE
Documentation or steps to integrate it

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#82]
Hi,
I just purchased the module today to use it in ios+android.

I already configured the certificate for APN service and got API key and id for GCM. But, then I'm clueless how to use in my app.

Sorry, I'm very new to Appcelerator. If you could give advise  or the steps how to use it in my app and where to send the notification (ACS or APN or GCM) would be really helpful.

Thanks in advance for your assistance. 

Many Thanks & Regards,

**Comment by somefakeuser** [comment]
Sorry, this is the module I bought https://marketplace.appcelerator.com/apps/10615#!overview

**Comment by somefakeuser** [comment]
I used titanium 3.5.1. Would it be ok?

**Comment by arleyandrada** [comment]
Besides the documentation and example that accompanies the module (folders documentation and example) you can check the sample project that I made available at the GitHub in https://github.com/arleyandrada/PushClient

As a server side (push notification provider) I suggest you to use Parse.com, which have a good documentation and is very simple.

Ok to Titanium 3.5.1 SDK.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks. Where do I add the below usage code? alloy.js or app/controller/index.js

Sorry I'm very new to appcelerator. 

```
var PushClient = require('br.com.arlsoft.pushclient');

var registerOptions = { GCMSenderId : 'put-your-google-cloud-messaging-sender-id-here', APNTypes : [ PushClient.NOTIFICATION_TYPE_BADGE, PushClient.NOTIFICATION_TYPE_ALERT, PushClient.NOTIFICATION_TYPE_SOUND ] };

if (OS_IOS) { var acceptAction = PushClient.createAction({ identifier: 'ACCEPT_IDENTIFIER', title: 'Accept', activationMode: PushClient.NOTIFICATION_ACTIVATION_MODE_FOREGROUND, destructive: false, authenticationRequired: true }); var rejectAction = PushClient.createAction({ identifier: 'REJECT_IDENTIFIER', title: 'Reject', activationMode: PushClient.NOTIFICATION_ACTIVATION_MODE_BACKGROUND, destructive: true, authenticationRequired: false }); var downloadContent = PushClient.createCategory({ identifier: 'APPROVE_CONTENT', actionsForMinimalContext: [acceptAction, rejectAction], actionsForDefaultContext: [acceptAction, rejectAction] }); registerOptions.Categories = [downloadContent]; }

var eventSuccess = function(event) { alert('Registration Id : ' + event.registrationId); };

var eventError = function(event) { switch (event.code) { case PushClient.ERROR_SENDER_ID: alert('Error : Undefined GCMSenderId'); break; case PushClient.ERROR_PLAY_SERVICES: alert('Error : Google Play Services not available'); break; case PushClient.ERROR_NOT_SUPPORTED: alert('Error : Not supported error'); break; case PushClient.ERROR_REGISTER: alert('Error : Unable to register this device'); break; case PushClient.ERROR_UNREGISTER: alert('Error : Unable to unregister this device'); break; default: alert('Error : Unknown error'); } };

var eventCallback = function(event) { if (event.mode == PushClient.MODE_FOREGROUND) { alert('Callback in Foreground : ' + JSON.stringify(event.data)); } else if (event.mode == PushClient.MODE_CLICK) { alert('Callback from Click : ' + JSON.stringify(event.data)); } else if (event.mode == PushClient.MODE_BACKGROUND) { PushClient.endBackgroundHandler(event.data.handlerId); alert('Callback from Silent:nn' + JSON.stringify(event.data)); } else if (event.mode == PushClient.MODE_ACTION) { alert('Callback from Action:nn'+event.category+'n'+event.identifier+'nn' + JSON.stringify(event.data)); } };

PushClient.addEventListener(PushClient.EVENT_SUCCESS, eventSuccess); PushClient.addEventListener(PushClient.EVENT_ERROR, eventError); PushClient.addEventListener(PushClient.EVENT_CALLBACK, eventCallback);

PushClient.registerPush(registerOptions);
```

**Comment by arleyandrada** [comment]
The example project at my GitHub repository suggests a place to put the "Push Client Module calls".
https://github.com/arleyandrada/PushClient

There is another options, accordingly to your preferences and your project structure.

There is a single requirement: the "addEventListener" and "registerPush" calls need to be called at every app startup, regardless if the device is already registered.

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks. I followed the code and added those into aap/controllers/index.js. However, when I ran the app I got the following error:

```
[WARN] :   couldn't find file br_com_arlsoft_pushclient_js
[INFO] :   registerPush...
[INFO] :   eventError:{"code":3,"success":false,"error":"no valid 'aps-environment' entitlement string found for application","bubbles":true,"type":"PushClient_Error","source":{"id":"br.com.arlsoft.pushclient"},"cancelBubble":false}
```

**Comment by arleyandrada** [comment]
This error message suggests that the module is not installed.
http://docs.appcelerator.com/titanium/3.0/#!/guide/Using_a_Module

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi,
The module was installed properly. And I saw during the beginning of the compilation in the console it was found. But when I launched my app I got the following in console:

```
[WARN] :   couldn't find file br_com_arlsoft_pushclient_js
[INFO] :   eventError:{"code":3,"success":false,"error":"no valid 'aps-environment' entitlement string found for application","bubbles":true,"type":"PushClient_Error","source":{"id":"br.com.arlsoft.pushclient"},"cancelBubble":false}
```

I was wondering should it be looking for the file br.com.arlsoft.pushclient.js instead of br_com_arlsoft_pushclient_js

Besides, when the app is launched I also got the following alert message:

Unable to register this device. no valid 'aps-environment' entitlement string found for application

Please help. I got stuck. I'm trying to user parse.com after purchased your mobile.

**Comment by arleyandrada** [comment]
The module is not well installed!

Try to read this issue history:
https://github.com/arleyandrada/PushClient/issues/17

To able an iOS app to receive push notifications you need to follow some configuration steps:

https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringPushNotifications/ConfiguringPushNotifications.html

https://parse.com/tutorials/ios-push-notifications

Regards,

P.S.: It is not possible to receive push notifications with iOS emulator.

Arley

**Comment by somefakeuser** [comment]
Hi,
I sorted everything in IOS.

But, when I'm trying in android emulator it's saying Google Play Service not available. SERVICE_MISSING.

Please advise.

**Comment by arleyandrada** [comment]
With Android Emulator you can receive push notifications, but you need to install the Google Play Services in the emulated device.

http://developer.android.com/google/play-services/setup.html

It is a bit easier if you use Genymotion emulated devices.

https://www.genymotion.com

The easier way is to run and debug your app straight in a real device.

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi, many thanks for your help so far. I have been using real device to test it. But still didn't work in android. I followed your suggestion here https://github.com/arleyandrada/PushClient/issues/79.

I have the following in my app/config.json file:

```
"ParseGCMSenderId": "1076345567071"
```

I also added the following into app/controllers/index.js

```
    //Push Notification
    if (OS_IOS) {
        var issue17030 = Ti.Network.registerForPushNotifications;
        var issue17030iOS8 = Ti.App.iOS.registerUserNotificationSettings;
    }

    var PushClient = require('br.com.arlsoft.pushclient');
    var registerOptions = { GCMSenderId : '1076345567071', APNTypes : [ PushClient.NOTIFICATION_TYPE_BADGE, PushClient.NOTIFICATION_TYPE_ALERT, PushClient.NOTIFICATION_TYPE_SOUND ] };
    var Parse = require('parse');
```

Do you think is there anything other place I need to add/edit the GCMSenderID to make it work fro Android device? It's already working fine in IOS.

**Comment by arleyandrada** [comment]
What is the problem you are facing at the moment?
What error message is displayed or which wrong behavior?

Check your JSON payload data:
https://github.com/arleyandrada/PushClient/issues/69

Regards,

Arley

**Comment by somefakeuser** [comment]
I'm trying to send push notification to android using parse.com. But, so far it's not sending although in parse I can see 9 android devices installed the updated version of the apps. One of my colleague tried to installed the apk file into his nexus 5. After that i sent another push. But, he didn't receive it.

**Comment by arleyandrada** [comment]
Have you checked that you have configured your application to Parse.com correctly?

Parse.com -> Your App -> Settings -> Push -> GCM Push Credentials

Keep the fields "Sender ID" and "API Key" empty to use the Parse.com GCM Sender ID (1076345567071).

Remove all registered devices at Parse.com (Your App -> Core); Check if the "Parse.com GCM Sender ID" is used in your app; Rebuild and run your project again; Check if there is new registered devices at Parse.com.

Finally, use Parse.com to send an JSON message:

{ "alert" : "Hello World!" }

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks a lot. Removing sender id and api key from parse.com settings page did the trick. It's working now. Many thanks again.
