### ISSUE TITLE
pushclient support

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#84]
Hi,
i’ve purchased your module
but i can’t install it in my alloy application.

Which folder should I install the files?

Tnx for any help.

**Comment by arleyandrada** [comment]
Check this GitHub repo:

https://github.com/arleyandrada/PushClient

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,
tnx so much for your replay.

I’ve installed the files as in your example on github but i’ve always

```
Couldn't find module: br.com.arlsoft.pushclient for architecture: i3
```

Where i can find the br.com.arlsoft.pushclient file in your package?

Tnx for your help

**Comment by arleyandrada** [comment]
Try to read this issue history:

https://github.com/arleyandrada/PushClient/issues/17
