### ISSUE TITLE
Pushclient Titanium Module

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#85]
Hello,
We bought your module pushclient but we can not get in the click event of the notification.
We can not find a specific example, please help us.
Regards

**Comment by arleyandrada** [comment]
Within my PushClient module there is a folder named "example" and another folder named "documentation" with all that you need to code an app with my module.

If you coded the event listeners as showed in the example, maybe you need to check if the module is initialized (call to the registerPush method) and the event listeners registered at every app startup (regardless if the device was registered before).

Please let me know if it works for you.

Regards,

Arley
