### ISSUE TITLE
PushClient questions

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#86]
Hi there. I am currently using Urban Airship and they recently required the use of JDK 1.7 and Titanium only uses 1.6. 

So i stumbled upon PushClient and wanted to see if this would work for me.

First, does this module require that I use an Alloy project?

Second, does this module have an inbox where the receive push notifications can be collected and viewed at a later time.

Also I apologize, I just noticed that there is a questions tab on your marketplace. I have never seen this before. I have to admit I am blown away before I've even purchased this module as you guys have already surpassed everyone else as far as support.

Thanks in advance,

**Comment by arleyandrada** [comment]
No, my module is not Alloy dependent.
Only my example code and example project was coded with Alloy.

No, my module does not handle any visual UI element beyond the push notification, but you can code your own "inbox" using my PushClient module.

For more questions, take a look at my issue history at:
https://github.com/arleyandrada/PushClient

Regards,

Arley

**Comment by somefakeuser** [comment]
Thanks Arley, I recently purchased your module and put everything into place but when I run the app I get this error:

```
[ERROR] :  TiVerify: (Timer-0) [263,5260] License violation detected. Unlicensed module(s) detected. You must be a subscriber to use one or more of the modules included with this project.. Please contact Appcelerator Support.
```

I contacted support but I was wondering if you knew how I could fix this?

**Comment by arleyandrada** [comment]
All your developers run Titanium Studio logged with your company account?

Within your company account in purchased products from Appcelerator Marketplace you need to assign the seats to your developers account (same user logged at Titanium Studio).

Have you checked this?

Unfortunately it is a Titanium problem.

Another users solved this problem creating new blank project and others with this workarround:

http://stackoverflow.com/questions/12106437/appcelerator-titanium-module-verification-issue-unlicensed-modules

Regards,

Arley

**Comment by somefakeuser** [comment]
Hi Arley, yes everything was attached correctly. I ended up removing all my modules from my app and then cleaning. Then re added your module and cleaned again. Magically that did the trick. thank you
