### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#9]
Hi,

after installing the modules in Titanium Studio I tried to start the app.js from the folder /iphone/examples on my iphone and all I get is the following error.

Can You help me?

Best regards,
Ralf

```
[ERROR] :  Script Error {
[ERROR] :      backtrace = "#0 () at :0";
[ERROR] :      line = 1;
[ERROR] :      message = "Can't find variable: OS_ANDROID";
[ERROR] :      name = ReferenceError;
[ERROR] :      sourceId = 38284000;
[ERROR] :      sourceURL = "file://localhost/var/mobile/Applications/D2B78A08-7C1E-40D3-B43D-15931CA006B3/PN2.app/app.js";
[ERROR] :  }
```

**Comment by arleyandrada** [comment]
Hi,

Sorry by delayed response.

Which Titanium SDK version are you using in your app?

My PushClient module requires minimum Titanium SDK 3.2.1 version.

Anyway, the OS_ANDROID variable is defined by Alloy which also appears not be installed.
http://docs.appcelerator.com/titanium/3.0/#!/guide/Alloy_Quick_Start

If you want to workaround the OS_ANDROID variable problem, you can set this variable with info from Titanium native variables as I show below:

```
var OS_ANDROID = Ti.Platform.osname === "android";
```

Please let me know if it works for you or if I can help you with anything else.

Thanks,

Arley

**Comment by somefakeuser** [comment]
Hi Arley,

my Version is 3.3.0. and I’m new to Titanium. 

My ProjectTemplate is a Classic Template and not an Alloy. 
Your workaround solves the problem and when I run Your  code
in an AlloyTemplate everything is fine too.

Thank You for the fast help,

**Comment by arleyandrada** [comment]
Hi,

I need more info to be able to help you:

What is the push notification server / service are you using?
What is the message / payload data you are sending to the device?
Are you running your app on iOS or Android?
What is the Titanium SDK version you are using in your app?

Are you getting an successful registration?
Have you made a test with your app in foreground and after an successful registration?

I wait for your response.

Regards,

P.S.: I'm from Brazil.

Arley Maria

**Comment by arleyandrada** [comment]
Hi,

Have you solved the problem by yourself?

Please let me know if you need some help.

Regards,

Arley Maria
