### ISSUE TITLE
PushClient.unregisterPush(); question

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#91]
Hi Arley,

Things are working great with this module! I had a question as to how to get PushClient.unregisterPush(); to do something. 

When i register I see everything pop into Parse's database, but when i call the unregister push I would expect to see the data erased from Parse's database. It looks as if nothing happens. 

Is there something I'm missing? Thx

**Comment by arleyandrada** [comment]
My module do not call Parse's api.
All the Parse integration code was written in JavaScript as a sample.

If you want to remove the device registration from Parse you need to write and call the specific api.
https://parse.com/docs/rest/guide#push-notifications-deleting-installations

Regards,

Arley

**Comment by somefakeuser** [comment]
Ok thank you, have a good day.
