### ISSUE TITLE
Not able to build app

### ISSUE THREAD

**Issue by ginixsan** [arleyandrada/PushClient#93]
Hi, just bought yesterday the module and when I try to build it gives this error and fails to build:
[ERROR] :  2015-06-03 19:47:05.555 xcodebuild[27410:117912] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/asmapp.build/Debug-iphoneos/asmapp.build/Objects-normal/arm64/asmapp normal arm64
[ERROR] :  (1 failure)
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/ginessanchis/.appcelerator/install/4.0.1/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
Using Appcelerator Studio, build: 4.0.0.201505202026
SDK : 4.0.0.GA
Went to Xcode and gives this errors in there: 
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_TiAppiOSProxy", referenced from:
      _OBJC_CLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
     (maybe you meant: _OBJC_CLASS_$_TiAppiOSProxyHack)
  "_OBJC_METACLASS_$_TiAppiOSProxy", referenced from:
      _OBJC_METACLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)
     (maybe you meant: _OBJC_METACLASS_$_TiAppiOSProxyHack)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  "_OBJC_CLASS_$_TiAppiOSProxy", referenced from:

```
  _OBJC_CLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)


 (maybe you meant: _OBJC_CLASS_$_TiAppiOSProxyHack)
```

  "_OBJC_METACLASS_$_TiAppiOSProxy", referenced from:

```
  _OBJC_METACLASS_$_TiAppiOSProxyHack in libbr.com.arlsoft.pushclient.a(TiAppiOSProxyHack.o)


 (maybe you meant: _OBJC_METACLASS_$_TiAppiOSProxyHack)
```

ld: symbol(s) not found for architecture i386

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ginixsan** [comment]
Just in case.. if I remove the sparkplugin....still getting error...

[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/asmapp.build/Debug-iphoneos/asmapp.build/Objects-normal/arm64/asmapp normal arm64
[ERROR] :  (1 failure)
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/ginessanchis/.appcelerator/install/4.0.1/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)

**Comment by arleyandrada** [comment]
Hi,

Check this issue:
https://github.com/arleyandrada/PushClient/issues/55

Regards,

Arley

**Comment by ginixsan** [comment]
Yes! it was that!! forgot to include it! :)
