### ISSUE TITLE
Can't get notification when app closed on Android

### ISSUE THREAD

**Issue by somefakeuser** [arleyandrada/PushClient#94]
Hi,

Today, I bought your Titanium  module named "Pushclient".
It works really well for iOS but I can't obtain notifications in "notifications center" from Android if app being closed.
When app is alive, there is no problem (I've a message on screen).
I use exactly your exemple code (alloy.js) minus "parse" part.
Can you, please, help me ?

**Comment by arleyandrada** [comment]
Check this closed issue:
https://github.com/arleyandrada/PushClient/issues/37

Format your JSON payload data with "alert" or "text" attributes.
Something like this:

```
{
"alert" : "Hello World!"
}
```

Regards,

Arley

**Comment by somefakeuser** [comment]
You're right. It was ma Laravel sending module which ignore "alert" entry.
Thanks for your answer.
Your module is really good. I'm glad to have buy it :)

Regards from France
