### ISSUE TITLE
Problems with idle or else

### ISSUE THREAD

**Issue by flaviolacer** [arleyandrada/PushClient#96]
I don't know the cause, but i'm receiving this error after some time the app start:

[ERROR] :  BroadcastReceiver: BroadcastReceiver trying to return result during a non-ordered broadcast
[ERROR] :  BroadcastReceiver: java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
[ERROR] :  BroadcastReceiver:   at android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:783)
[ERROR] :  BroadcastReceiver:   at android.content.BroadcastReceiver.setResultCode(BroadcastReceiver.java:549)
[ERROR] :  BroadcastReceiver:   at br.com.arlsoft.pushclient.GCMBroadcastReceiver.onReceive(GCMBroadcastReceiver.java:31)
[ERROR] :  BroadcastReceiver:   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2635)
[ERROR] :  BroadcastReceiver:   at android.app.ActivityThread.access$1700(ActivityThread.java:149)
[ERROR] :  BroadcastReceiver:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
[ERROR] :  BroadcastReceiver:   at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  BroadcastReceiver:   at android.os.Looper.loop(Looper.java:211)
[ERROR] :  BroadcastReceiver:   at android.app.ActivityThread.main(ActivityThread.java:5321)
[ERROR] :  BroadcastReceiver:   at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  BroadcastReceiver:   at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  BroadcastReceiver:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
[ERROR] :  BroadcastReceiver:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

Do you know what it is?

MACOS
Titanium 4.1.0.GA / 4.0.0.GA
Android 5.0.2

**Comment by arleyandrada** [comment]
It seems that Google once again broke backwards compatibility and they are sending non-ordered broadcasts to GCM in some cases. The (deprecated) official document recommends to use setResultCode - but this is not the case anymore.

Please, contact me by email (arley@arlsoft.com.br) and identity yourself (user responsible for purchasing) to receive an updated module version prior to release at Appcelerator Marketplace.

**Comment by arleyandrada** [comment]
Problem solved with latest PushClient version (1.9) for Android.
