### ISSUE TITLE
[Android] Eventcallback fired twice?

### ISSUE THREAD

**Issue by nubu** [arleyandrada/PushClient#97]
Hey,

tried to implement this lib in my current Application (SDK 4.1) on Android and noticed that the callback is executed twice on each push. (Using Kinvey as Provider)

Any idea/hint about this? 

best, Nico

**Comment by arleyandrada** [comment]
Hi Nico,

It's everything OK with SDK 4.1, but all previously reported issues about multiple callback execution was explained by multiple calls to the addEventListener or registerPush methods.

Please recheck, put some log and try to assert that there is no multiple event registrations.

If you do not find the problem, you can send me some sample code with which I can simulate this issue.

Regards,

Arley
