### ISSUE TITLE
Push sound not play in background mode in Android

### ISSUE THREAD

**Issue by DanielBcnicode** [arleyandrada/PushClient#98]
Hi, I use your module in Android, all run ok except in background mode. 
The app is made in Titanium classic, and I tested in titanium SDK 3.5.1GA and 4.0.0GA
In this mode the notification show the alert, vibrate but not play the sound.
I put the sound file in platform/android/assets/tone.wav, in platform/android/assets/sound/tone.wav, Resources/android/assets/tone.wav , Resources/android/assets/sound/tone.wav , Resources/sound/tone.wav and Resources/tone.wav but not play.
In iOS I don't have any problem but in Android..... 
I need help!!!!
Thanks and sorry for my poor English.
Daniel Martinez

**Comment by arleyandrada** [comment]
Hi Daniel,

Did you find a bug!
I sent to your email a new fixed version of my module.

Remove previous version, install the new module version, clean your project and build it again.

Put your custom audio file (wav or mp3) within the raw resource folder:

```
/platform/android/res/raw/youraudiofile.wav
```

Send a JSON payload data like below:

```
{
"alert" : "Custom sound",
"sound" : "youraudiofile"
}
```

Regards,

P.S.: Sorry by my poor english too! I'm from Brazil.

Arley
