### ISSUE TITLE
Could not find all required Titanium Modules: [ERROR] :     id: br.com.arlsoft.pushclient

### ISSUE THREAD

**Issue by zhaobinqu** [arleyandrada/PushClient#99]
Hi,

After downloaded the project, I imported it into Titanium as a mobile project. When I tried to installed it on the phone, a error came out. 
  [WARN] :   Could not find a valid Titanium module id=br.com.arlsoft.pushclient version=latest  platform=android deploy-type=test
  [INFO] :   Found Titanium module id=ti.map version=2.2.3 platform=android deploy-type=test path=/Library/Application Support/Titanium/modules/android/ti.map/2.2.3
  [INFO] :   Found Titanium module id=ti.cloud version=3.2.8 platform=commonjs deploy-type=test path=/Library/Application Support/Titanium/modules/commonjs/ti.cloud/3.2.8
  [ERROR] :  Could not find all required Titanium Modules:
  [ERROR] :     id: br.com.arlsoft.pushclient    version: latest     platform: android   deploy-type: test
  [ERROR] Application Installer abnormal process termination. Process exit value was 1

Thanks,
Robin

**Comment by arleyandrada** [comment]
Hi Robin,

https://github.com/arleyandrada/PushClient/blob/master/README.md

PushClient is a Titanium Module that brings Push Notification capabilities to your iOS (APNs) and Android (GCM) apps.

This repository contains a simple Titanium Mobile project with an usage sample of the PushClient module.

Buy and download the PushClient module through the Appcelerator Marketplace.

Regards,

Arley
